#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

exec 1> "$1"

header="png.h"
define="-DHAVE_LIBPNG"
path="${SYSDEP_STDINC}"
pkg="libpng12"

case "${SYSDEP_SYSTYPE}" in
  sunos)
    path="${path} /usr/sfw/include"
    ;;
  darwin)
    path="${path} /sw/include"
    ;;
  *)
    ;;
esac

FLAGS=`try_config_bin "libpng-config" "--I_opts --cppflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  error "try_config_bin failed"
fi

FLAGS=`try_pkg_config "${pkg}" "--cflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  error "try_pkg_config failed"
fi

FLAGS=`try_manual_search "${header}" "${path}" "-I" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  error "try_manual_search failed"
fi

exit 0
