#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

search="NO"
header="png.h"
define="-DSYSD_HAVE_LIBPNG"
path="/usr/include /usr/local/include"

sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
if [ x"${sys}" != x ]
then
  case "${sys}" in
  sunos)
    path="${path} /usr/sfw/include "
    search="YES"
    ;;
  *) ;;
  esac
fi

# for systems that don't have libpng-config
if [ "${search}" = "YES" ]
then
  search_header "${header}" "${path}"
  if [ $? -ne 0 ]
  then
    error "could not locate ${header}"
  else
    echo "${define}"
  fi
  exit 0
fi

# default libpng-config system
flist=`libpng-config --I_opts --cppflags`
err=$?
flags=""

if [ ${err} -ne 0 ]
then
  error "could not locate libPNG includes"
else
  for f in ${flist}
  do
    flags="${flags} $f"
  done
  echo ${flags} ${define}
fi
