#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

sd_tmp="sysdeps.out"
f1_tmp="_uint32.h"
echo "SYSDEPS uint32 run create ${f1_tmp}"

sd_out="${SYSDEP_OUTDIR}/${sd_tmp}"
f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

./uint32 ${f1_tmp} ${sd_tmp}
if [ $? -eq 0 ]
then
  cp ${f1_tmp} ${f1_out}
  cat ${sd_tmp} >> ${sd_out}
else
  exit 1
fi
