#!/bin/sh

do_clean()
{
  rm -f uint32_make
}

fatal()
{
  echo "fatal: $1" 1>&2
  do_clean
  exit 1
}

tempuint="$1"
tempsys="$2"

${SYSDEP_CC} -o uint32_make uint32_make.c
if [ $? -ne 0 ]; then fatal "error compiling uint32_make"; fi
./uint32_make 1>${tempuint} 2>>${tempsys}
if [ $? -ne 0 ]; then fatal "could not get 32-bit unsigned ints"; fi

do_clean
exit 0
