#!/bin/sh

cleanup()
{
  rm -f try_int1 try_int1.o \
        try_int2 try_int2.o \
        try_stdint try_stdint.o
}

fatal()
{
  SYSDEP_FATAL "$1"
  cleanup
  exit 1
}

have_it()
{
  type="$1"
  extra="$2"

  cat >> "${temp_f}" <<EOF
#ifndef _INT16_H
#define _INT16_H

$extra
typedef $type int16;

#endif
EOF
  echo "int16: ${type}" >> "${temp_sys}"
  cleanup
  exit 0
}

temp_f="$1"
temp_sys="$2"

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o try_stdint.o try_stdint.c 1>/dev/null 2>&1
${SYSDEP_LD} -o try_stdint try_stdint.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  have_it "int16_t" "#include <stdint.h>"
fi

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o try_int1.o try_int1.c 1>/dev/null 2>&1
${SYSDEP_LD} -o try_int1 try_int1.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  type=`./try_int1`
  if [ $? -eq 0 ]
  then
    have_it "${type}"
  else
    ${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o try_int2.o try_int2.c 1>/dev/null 2>&1
    ${SYSDEP_LD} -o try_int2 try_int2.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
    if [ $? -eq 0 ]
    then
      type=`./try_int2`
      if [ $? -eq 0 ]
      then
        have_it "${type}"
      fi
    fi
  fi
fi

conf=`${SYSDEP_LINE} 1 < CONFIG`
SYSDEP_INFO "falling back to ${conf}"
type=`${SYSDEP_FILE} get "${conf}" ""`
if [ ! -z ${type} ]
then
  fatal "could not get signed 16 bit integer type"
fi

cleanup
exit 0
