#!/bin/sh

fout="$1"
sdout="$2"

cleanup()
{
  rm -f trycarbon trycarbon.o
  exit 0
}

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trycarbon.o trycarbon.c 1>/dev/null 2>&1
${SYSDEP_LD} -o trycarbon trycarbon.o -framework Carbon ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '-framework Carbon' >> "${fout}"
  echo 'carbon: yes' >> "${sdout}"
else
  echo >> "${fout}"
  echo 'carbon: no' >> "${sdout}"
fi

cleanup
