#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

do_clean()
{
  rm -f make-byteorder
}

fatal()
{
  echo "fatal: $1" 1>&2
  do_clean
  exit 1
}

temph="$1"
tempsys="$2"

${SYSDEP_CC} -o make-byteorder make-byteorder.c
if [ $? -ne 0 ]; then fatal "error compiling make-byteorder"; fi

./make-byteorder 1>${temph} 2>>${tempsys}
if [ $? -ne 0 ]; then fatal "could not create make-byteorder header"; fi

do_clean
exit 0
