#!/bin/sh

exec 1> "$1"

path="${SYSDEP_STDLIB}"
pkg="jack"
lib="lib${pkg}.${SYSDEP_LIBSUFFIX}"

FLAGS=`${SYSDEP_TRY_PKG_CONFIG} "${pkg}" "--libs" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS}
  exit 0
else
  ${SYSDEP_ERROR} "pkg-config failed"
fi

FLAGS=`${SYSDEP_TRY_MANUAL} "${lib}" "${path}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} "-l${pkg}"
  exit 0
else
  ${SYSDEP_ERROR} "manual search failed"
fi

exit 0
