#!/bin/sh

if [ $# -lt 1 ]
then
  echo "usage: source" 1>&2
  exit 1
fi

CC=`head -n 1 conf-cc`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-cc" 1>&2
  exit 1
fi
CFLAGS="${CFLAGS} `head -n 1 conf-cflags 2>/dev/null`"

SYSTYPE=`head -n 1 conf-systype`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-systype" 1>&2
  exit 1
fi

CCTYPE=`head -n 1 conf-cctype`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-cctype" 1>&2
  exit 1
fi

# read in optional flag file
if [ -f "conf-ccfflist" ]
then
  for f in `cat "conf-ccfflist"`
  do
    FLAGS=`cat $f 2>/dev/null`
    CFLAGS="${CFLAGS} ${FLAGS}"
  done
fi

out=`echo "$1" | awk -F. '{print $1}'`
src="$1"
shift

# read in optional flag file
if [ -f "${out}.iff" ]
then
  for f in `cat "${out}.iff"`
  do
    targ="`dirname $out`/`dirname $f`/`basename $f`"
    FLAGS="`cat $targ 2>/dev/null`"
    CFLAGS="${CFLAGS} ${FLAGS}"
  done
fi

case ${CCTYPE} in
  GCC)
    case ${SYSTYPE} in
      DARWIN)
        # On Darwin >= 8, produce fat binaries
        release=`uname -r | awk -F. '{print $1}'`
        if [ ${release} -gt 7 ]
        then
          if [ -d /Developer/SDKs/MacOSX10.4u.sdk ]
          then
            exec ${CC} \
              -arch ppc \
              -arch i386 \
              -isysroot /Developer/SDKs/MacOSX10.4u.sdk \
              -o ${out}.o -c ${src} ${1+"$@"} ${CFLAGS}
          fi
        fi
        ;;
      *)
        ;;
    esac
    ;;
  *)
    ;;
esac

exec ${CC} -o ${out}.o -c ${src} ${1+"$@"} ${CFLAGS}
