#include "ch_flags.h"

int main()
{
  /* mostly generated by tools/genchkcode.sh */

#ifdef HAVE_CHFLAGS
  printf("system has ch_flags\n");
#else
  printf("system does not have ch_flags\n");
#endif
#ifdef HAVE_LIBPNG
  printf("system has png\n");
#else
  printf("system does not have png\n");
#endif
#ifdef HAVE_SDL
  printf("system has sdl\n");
#else
  printf("system does not have sdl\n");
#endif
#ifdef HAVE_SDL_MIXER
  printf("system has sdl-mixer\n");
#else
  printf("system does not have sdl-mixer\n");
#endif
#ifdef HAVE_SDL_IMAGE
  printf("system has sdl-image\n");
#else
  printf("system does not have sdl-image\n");
#endif
#ifdef HAVE_SDL_TTF
  printf("system has sdl-ttf\n");
#else
  printf("system does not have sdl-ttf\n");
#endif
#ifdef HAVE_LIBSNDFILE
  printf("system has sndfile\n");
#else
  printf("system does not have sndfile\n");
#endif
#ifdef HAVE_JACK
  printf("system has jack\n");
#else
  printf("system does not have jack\n");
#endif

  return 0;
}
