#!/bin/sh
LD="`head -n 1 conf-ld`"
if [ -f 'conf-ldfflist' ]
then
  for f in `cat conf-ldfflist`
  do
    name=`echo $f | tr [a-z] [A-Z] | tr '\-\.\,\;\:' '_'`
    echo ${name}=\"`cat $f`\"
    ALL_LIBS="${ALL_LIBS} ${name}"
  done
fi

# libfile detection
echo 'out="$1"; shift'
echo 'objs=""'
echo 'for arg in ${1+"$@"}'
echo 'do'
echo '  suffix=`echo ${arg} | awk -F\.' "'{print \$NF}'"'`'
echo '  if [ "${suffix}" = "lib" ]'
echo '  then'
echo '    file=`cat ${arg}`'
echo '    if [ $? -ne 0 ]'
echo '    then'
echo '      exit 1'
echo '    fi'
echo '    objs="${objs} ${file}"'
echo '  else'
echo '    objs="${objs} ${arg}"'
echo '  fi'
echo 'done'

# main exec
echo exec "${LD}" '-o "$out" ${objs} \'

for f in ${ALL_LIBS}
do
  echo '  ${'$f'} \'
done
