#!/bin/sh
CC="`head -n 1 conf-cc`"
if [ -f 'conf-ccfflist' ]
then
  for f in `cat conf-ccfflist`
  do
    name=`echo $f | tr [a-z] [A-Z] | tr '\-\.\,\;\:' '_'`
    echo ${name}=\"`cat $f`\"
    ALLFLAGS="${ALLFLAGS} ${name}"
  done
fi
echo exec "$CC" '-o $1.o -c $2 \'
for f in ${ALLFLAGS}
do
  echo '  ${'$f'} \'
done

