#!/bin/sh

sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"

echo 'main="$1"; shift;'
echo 'vmj="`cat ${main}.vmj 2>&-`"'
echo 'vmn="`cat ${main}.vmn 2>&-`"'
echo 'suf="`./sosuffix`"'

echo
echo 'if [ "x${vmj}" != "x" ]'
echo 'then'
echo ' if [ "x${vmn}" != "x" ]'
echo ' then'
case "$sys" in
  darwin)
    echo '   exec echo ${main}.${vmj}.${vmn}.${suf}'
    echo ' else'
    echo '   exec echo ${main}.${vmj}.${suf}'
    ;;
  *)
    echo '   exec echo ${main}.${suf}.${vmj}.${vmn}'
    echo ' else'
    echo '   exec echo ${main}.${suf}.${vmj}'
    ;;
esac 
echo ' fi'
echo 'else'
echo ' exec echo ${main}.${suf}'
echo 'fi'
