#!/bin/sh
sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
echo 'main="$1"; shift';
echo 'rm -f "$main.a"'
echo 'ar cr "$main.a" ${1+"$@"}'
case "$sys" in
  sunos) ;;
  unix_sv*) ;;
  irix64-*) ;;
  irix-*) ;;
  dgux-*) ;;
  hp-ux-*) ;;
  sco*) ;;
  *) echo 'ranlib "$main.a"'
    ;;
esac
