#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

exec 1> "$1"

args="-lalut"
path="${SYSDEP_STDLIB} /usr/X11R6/lib"
lib="libalut.so"

# What a hack.
case ${SYSDEP_OS} in
  SD_SYSINFO_OS_DARWIN)
    lib="libalut.dylib"
    args="-framework ALUT"
    path="/System/Library/Frameworks/ALUT.framework ${path}"
    if [ -d "/System/Library/Frameworks/ALUT.framework" ]
    then
      ${SYSDEP_UTIL_ECHO} ${args}
      ${SYSDEP_UTIL_EXIT} 0
    fi
    ;;
  *)
    ;;
esac

FLAGS=`${SYSDEP_TRY_MANUAL} "${lib}" "${path}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  case ${SYSDEP_OS} in
    SD_SYSINFO_OS_DARWIN)
      ${SYSDEP_UTIL_ECHO} ${args}
      ${SYSDEP_UTIL_EXIT} 0
      ;;
    *)
      ${SYSDEP_UTIL_ECHO} ${FLAGS} ${args}
      ${SYSDEP_UTIL_EXIT} 0
      ;;
    esac
else
  SYSDEP_ERROR "manual search failed"
fi

${SYSDEP_UTIL_EXIT} 0
