#!/bin/sh

fout="$1"
sysdep="$2"

do_clean()
{
  rm -f trychflags
}

${SYSDEP_CC} -o trychflags trychflags.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  # have chflags
  cat > "${fout}" <<EOF
#ifndef _CH_FLAGS_H
#define _CH_FLAGS_H

#define CH_FLAGS_HAVE_CHFLAGS
#define CH_FLAGS_WORKING
#define HAVE_CHFLAGS

#endif
EOF
  echo "ch_flags: chflags" >> "${sysdep}"
  do_clean
  exit 0
fi

cat > "${fout}" <<EOF
#ifndef _CH_FLAGS_H
#define _CH_FLAGS_H

#endif
EOF
echo "ch_flags: none" >> "${sysdep}"
do_clean
exit 0
