#!/bin/sh

fout="$1"
sysdep="$2"

cleanup()
{
  rm -f trychflags trychflags.o
}

have_chflags()
{
  define=`${SYSDEP_LINE} 1 < defines`
  cat > "${fout}" <<EOF
#ifndef _CH_FLAGS_H
#define _CH_FLAGS_H

#define $define

#endif
EOF
  echo "ch_flags: chflags" >> "${sysdep}"
  cleanup
  exit 0
}

no_chflags()
{
  cat > "${fout}" <<EOF
#ifndef _CH_FLAGS_H
#define _CH_FLAGS_H

#endif
EOF
  echo "ch_flags: none" >> "${sysdep}"
  cleanup
  exit 0
}

conf=`${SYSDEP_LINE} 1 < config`

if [ ${SYSDEP_CROSS_COMPILE} -eq 1 ]
then
  have=`${SYSDEP_FILE} get "${conf}" ""`
  if [ ! -z "${have}" ]
  then
    case "${have}" in
      chflags)
        have_chflags;;
      none)
        no_chflags;;
      *)
        ${SYSDEP_ERROR} "unexpected value in ${conf}"
        no_chflags;;
    esac
  fi
fi

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trychflags.o trychflags.c >/dev/null 2>&1
${SYSDEP_LD} -o trychflags trychflags.o ${SYSDEP_LDFLAGS} >/dev/null 2>&1
if [ $? -eq 0 ];
then
  have_chflags;
else
  no_chflags;
fi
