#!/bin/sh

temp_f="$1"
temp_sys="$2"

args=""
file="lua.h"

FLAGS=`${SYSDEP_TRY_MANUAL} "${file}" "${SYSDEP_STDINC}" "-I" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo "${FLAGS} -DHAVE_LUA " >> "${temp_f}"
  echo "lua-flags: ${FLAGS} -DHAVE_LUA " >> "${temp_sys}"
  exit 0
fi

#
# Lua uses versioned directories.
#

for DIRECTORY in ${SYSDEP_STDINC}
do
  if [ -d "${DIRECTORY}" ]
  then
    MAYBE_DIRECTORIES=`ls ${DIRECTORY} | grep lua`
    for DIRECTORY_EXT in ${MAYBE_DIRECTORIES}
    do
      if [ -f "${DIRECTORY}/${DIRECTORY_EXT}/${file}" ]
      then
        echo "-I${DIRECTORY}/${DIRECTORY_EXT} -DHAVE_LUA " >> "${temp_f}"
        echo "lua-flags: -I${DIRECTORY}/${DIRECTORY_EXT} -DHAVE_LUA " >> "${temp_sys}"
        exit 0
      fi
    done
  fi
done

