#!/bin/sh

f1_tmp="libs-sdl-ttf"
echo "SYSDEPS sdl-ttf-libs run create ${f1_tmp}"

outdir="`head -n 1 ../conf-outdir`"
if [ -z "${outdir}" ]
then
  echo "fatal: outdir not defined" 2>&1
  exit 1
fi
outdir="../${outdir}"
f1_out="${outdir}/${f1_tmp}"

./sdl-ttf-libs ${f1_tmp}
cp ${f1_tmp} ${f1_out}
