#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
if [ x"$sys" != x ]
then
  case "$sys" in
  darwin)
    echo "-framework SDL_ttf"
    ;;
  *)
    echo "-lSDL_ttf"
    ;;
  esac
fi
