#!/bin/sh

fout="$1"
sysdeps="$2"

cat >> "${fout}" <<EOF
#ifndef _SD_DUP2_H
#define _SD_DUP2_H

EOF

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trydup2.o trydup2.c 1>/dev/null 2>&1
${SYSDEP_LD} -o trydup2 trydup2.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#define SD_HAVE_DUP2' >> "${fout}"
  echo 'sd-dup2: dup2' >> "${sysdeps}"
else
  echo 'sd-dup2: none' >> "${sysdeps}"
fi

echo '#endif' >> "${fout}"
rm -f trydup2 trydup2.o
