#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

fout="$1"
sysdeps="$2"

${SYSDEP_UTIL_CAT} >> "${fout}" <<EOF
#ifndef _SD_DUP2_H
#define _SD_DUP2_H

EOF

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trydup2.o trydup2.c 1>/dev/null 2>&1
${SYSDEP_LD} -o trydup2 trydup2.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_DUP2' >> "${fout}"
  ${SYSDEP_UTIL_ECHO} 'sd-dup2: dup2' >> "${sysdeps}"
else
  ${SYSDEP_UTIL_ECHO} 'sd-dup2: none' >> "${sysdeps}"
fi

${SYSDEP_UTIL_ECHO} '#endif' >> "${fout}"
${SYSDEP_UTIL_RM} -f trydup2 trydup2.o
