#!/bin/sh

fout="$1"
sd_out="$2"

cleanup()
{
  rm -f trysocket trysocket.o
  exit 0
}

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trysocket.o trysocket.c 1>/dev/null 2>&1
${SYSDEP_LD} -o trysocket trysocket.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo >> "${fout}"
  echo "socket-libs: " >> "${sd_out}"
  cleanup
fi

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trysocket.o trysocket.c 1>/dev/null 2>&1
${SYSDEP_LD} -o trysocket trysocket.c -lsocket ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '-lsocket' >> "${fout}"
  echo "socket-libs: -lsocket" >> "${sd_out}"
  cleanup
fi

touch "${sd_out}"
touch "${fout}"
