#!/bin/sh

exec 1> "$1"

header="portaudio.h"
define="-DHAVE_PORTAUDIO"
path="${SYSDEP_STDINC}"
pkg="portaudio"

case "${SYSDEP_SYSTYPE}" in
  darwin)
    path="${path} /sw/include"
    ;;
  *)
    ;;
esac

FLAGS=`${SYSDEP_TRY_MANUAL} "${header}" "${path}" "-I" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  ${SYSDEP_ERROR} "manual search failed"
fi

exit 0
