#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="libs-pthreads"
f2_tmp="flags-pthreads"
echo "SYSDEPS sd-pthreads run create ${f1_tmp} ${f2_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"
f2_out="${SYSDEP_OUTDIR}/${f2_tmp}"

./sd-pthreads ${f1_tmp} ${f2_tmp}
cp ${f1_tmp} ${f1_out}
cp ${f2_tmp} ${f2_out}
