#!/bin/sh

libs_out="$1"
flag_out="$2"

cleanup()
{
  rm -f trypthreads trypthreads.o
  exit 0
}

try_libs()
{
  ${SYSDEP_CC} -o trypthreads trypthreads.o 1>/dev/null 2>&1
  if [ $? -eq 0 ]
  then
    echo >> "${libs_out}"
    return 0
  fi
}

try_flags()
{
  ${SYSDEP_CC} -c -o trypthreads.o trypthreads.c 1>/dev/null 2>&1
  if [ $? -eq 0 ]
  then
    echo >> "${flags_out}"
    return 0
  fi
}

try_flags
try_libs
cleanup
