#!/bin/sh

pthr_libs_out="$1"
pthr_flag_out="$2"
pthr_rt_libs_out="$3"
pthr_rt_flag_out="$4"

PTHREAD_FLAGS="-DHAVE_PTHREADS -D_REENTRANT -D_POSIX_C_SOURCE=200112L"
PTHREAD_LIBS=""
PTHR_REALTIME_FLAGS="-DHAVE_PTHREADS_REALTIME"
PTHR_REALTIME_LIBS=""

cleanup()
{
  rm -f trypthreads tryptrealtime
  exit 0
}

try_one_pthread()
{
  ${SYSDEP_CC} ${PTHREAD_FLAGS} \
    -o trypthreads trypthreads.c ${PTHREAD_LIBS} 1>/dev/null 2>&1
  if [ $? -eq 0 ]
  then
    return 0
  else
    return 1
  fi
}

try_one_realtime()
{
  ${SYSDEP_CC} ${PTHREAD_FLAGS} \
    -o tryptrealtime tryptrealtime.c ${PTHREAD_LIBS} ${PTHR_REALTIME_LIBS} 1>/dev/null 2>&1
  if [ $? -eq 0 ]
  then
    return 0
  else
    return 1
  fi
}

try_pthreads()
{
  # default pthread libs
  try_one_pthread
  if [ $? -eq 0 ]; then return 0; fi

  PTHREAD_LIBS="-pthread"
  try_one_pthread
  if [ $? -eq 0 ]; then return 0; fi

  return 1
}

try_realtime()
{
  REALTIME_LIBS=""
  try_one_realtime
  if [ $? -eq 0 ]; then return 0; fi

  REALTIME_LIBS="-lrt"
  if [ $? -eq 0 ]; then return 0; fi

  return 1
}

case ${SYSDEP_CCTYPE} in
  SYSDEP_CCTYPE_SUN_C)
    PTHREAD_FLAGS="-mt ${PTHREAD_FLAGS}"
    PTHREAD_LIBS="${PTHREAD_LIBS} -lposix4"
    ;;
  SYSDEP_CCTYPE_SUN_CXX)
    PTHREAD_FLAGS="-mt ${PTHREAD_FLAGS}"
    PTHREAD_LIBS="${PTHREAD_LIBS} -lposix4"
    ;;
  *) ;;
esac

try_pthreads
if [ $? -eq 0 ]
then
  try_realtime
  if [ $? -eq 0 ]
  then
    echo "${PTHR_REALTIME_FLAGS}" >> "${pthr_rt_flag_out}"
    echo "${PTHR_REALTIME_LIBS}" >> "${pthr_rt_libs_out}"
  else
    touch "${pthr_rt_flag_out}"
    touch "${pthr_rt_libs_out}"
  fi
  echo "${PTHREAD_FLAGS}" >> "${pthr_flag_out}"
  echo "${PTHREAD_LIBS}" >> "${pthr_libs_out}"
else
  touch "${pthr_flag_out}"
  touch "${pthr_libs_out}"
fi

cleanup
