#!/bin/sh -x

libs_out="$1"
flag_out="$2"

FLAGS="-DHAVE_PTHREADS"
LIBS=""

cleanup()
{
  rm -f trypthreads trypthreads.o
  exit 0
}

try_compile()
{
  ${SYSDEP_CC} ${FLAGS} -o trypthreads trypthreads.c 1>/dev/null 2>&1
  if [ $? -eq 0 ]
  then
    return 0
  fi

  return 1
}

case ${SYSDEP_OS} in
  SYSDEP_OS_SUNOS)
    FLAGS="${FLAGS} -D_POSIX_C_SOURCE"
    ;;
  *)
    ;;
esac

try_compile
if [ $? -eq 0 ]
then
  echo "${FLAGS}" >> "${flag_out}"
  echo "${LIBS}" >> "${libs_out}"
else
  touch "${flag_out}"
  touch "${libs_out}"
fi

cleanup
