#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="flags-portaudio"
echo "SYSDEPS portaudio-flags clean ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

rm -f ${f1_tmp} ${f1_out}
