#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

finish()
{
  cat >> "${fout}" <<EOF
#finishif
EOF
  echo "cpuinfo: ${cpuinfo}" >> ${sysdeps}
  exit 0
}

fout="$1"
sysdeps="$2"
cpuinfo="none"

cat >> "${fout}" <<EOF
#ifndef _CPUINFO_H
#define _CPUINFO_H
EOF

finish
