#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

finish()
{
  cat >> "${fout}" <<EOF
#endif
EOF
  echo "cpuinfo: ${cpuinfo}" >> ${sysdeps}
  exit 0
}

fout="$1"
sysdeps="$2"
cpuinfo=""

cat >> "${fout}" <<EOF
#ifndef _CPUINFO_H
#define _CPUINFO_H
EOF

make 1>/dev/null
if [ $? -ne 0 ]
then
  finish
fi

finish
