#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

cleanup()
{
  rm -f float64_make float64_make.o
}

fatal()
{
  cleanup
  SYSDEP_FATAL "$1"
}

have_it()
{
  type="$1"
  ${SYSDEP_UTIL_CAT} >> ${temp64} << EOF
#ifndef _SD_FLOAT64_H
#define _SD_FLOAT64_H

#define SD_FLOAT64_SUPPORTED 1

typedef ${type} sd_float64;

#endif
EOF
  ${SYSDEP_UTIL_ECHO} "sd-float64: ${type}" >> "${tempsys}"
  cleanup
  ${SYSDEP_UTIL_EXIT} 0
}

unsupported()
{
  ${SYSDEP_UTIL_CAT} >> ${temp64} << EOF
#ifndef _SD_FLOAT64_H
#define _SD_FLOAT64_H

#endif
EOF
  ${SYSDEP_UTIL_ECHO} "sd-float64: none" >> "${tempsys}"
  cleanup
  ${SYSDEP_UTIL_EXIT} 0
}

temp64="$1"
tempsys="$2"

if [ ${SYSDEP_CROSS_COMPILE} -eq 0 ]
then
  ${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o float64_make.o float64_make.c
  ${SYSDEP_LD} -o float64_make float64_make.o ${SYSDEP_LDFLAGS}
  if [ $? -ne 0 ]
  then
    unsupported
    fatal "error compiling float64_make"
  fi
  type=`./float64_make`
  if [ $? -eq 0 ];
  then
    have_it "${type}"
  fi
fi

if [ -z "${type}" ]
then
  conf=`${SYSDEP_LINE} 1 < config`
  type=`${SYSDEP_FILE} get "${conf}" ""`
  if [ -z "${type}" ]
  then
    if [ ${SYSDEP_CROSS_COMPILE} -eq 1 ]
    then
      unsupported
      fatal "cross compiling and unable to read ${conf}"
    else
      unsupported
      fatal "unable to find appropriate float64 type and unable to read ${conf}"
    fi
  else
    have_it "${type}"
  fi
fi

cleanup
${SYSDEP_UTIL_EXIT} 0
