#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="flags-fastcgi"
echo "SYSDEPS fastcgi-flags run create ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

./fastcgi-flags ${f1_tmp}
cp ${f1_tmp} ${f1_out}
