#!/bin/sh

sd_tmp="sysdeps.out"
echo "SYSDEPS systype run"

outdir="`head -n 1 ../conf-outdir`"
if [ -z "${outdir}" ]
then
  echo "fatal: outdir not defined" 2>&1
  exit 1
fi
outdir="../${outdir}"
sd_out="${outdir}/${sd_tmp}"

./systype ${sd_tmp}
cat ${sd_tmp} >> ${sd_out}
