#!/bin/sh

exec 2>/dev/null
sys="$1"
arch=""

unamem="`uname -m | tr /: ..`"
case "$sys" in
  SYSDEP_OS_DARWIN)
    arch="`arch | tr /: ..`"
    ;;
  SYSDEP_OS_AIX)
    arch="`arch | tr /: ..`"
    ;;
  SYSDEP_OS_LINUX)
    case "$unamem" in
    i386|i486|i586|i686)
      arch="i386"
      ;;
    *)
      arch="$unamem"
      ;;
    esac
    ;;
  SYSDEP_OS_SUNOS)
    arch="`(uname -p || mach) | tr /: ..`"
    ;;
  SYSDEP_OS_HPUX)
    tmp="`file /stand/vmunix`"
    if [ $? -eq 0 ]
    then
      tmp="`echo $tmp | tr '/:[A-Z]' '..[a-z]'`"
    else
      tmp="standvmunix elf-64 executable object file - unknown unknown (lp64)"
    fi
    arch="`echo $tmp | awk '{print $7}'`"
    ;;
  SYSDEP_OS_NEXTSTEP)
    arch="`hostinfo | sed -n 's/^Processor type: \(.*\) (.*)$/\1/p' | tr /: ..`"
    ;;
  *)
    arch="$unamem"
    ;;
esac

case "$arch" in
  i386) echo 'SYSDEP_ARCH_X86' ;; 
  ppc) echo 'SYSDEP_ARCH_PPC' ;;
  pa-risc) echo 'SYSDEP_ARCH_PARISC' ;;
  ia64) echo 'SYSDEP_ARCH_IA64' ;;
  *) echo 'SYSDEP_ARCH_UNKNOWN' ;;
esac
