#!/bin/sh

if [ $# -ne 1 ]
then
  echo "sd-cpumodel: usage: os" 1>&2
  exit 1
fi

sys="$1"
model=""

case "$sys" in
  SD_SYSINFO_OS_DARWIN)
    model=`machine`
    ;;
  SD_SYSINFO_OS_VMS)
    model=""
    ;;
  SD_SYSINFO_OS_SUNOS)
    model=""
    ;;
  *)
    model_raw=`sysctl hw.model 2>/dev/null`
    model="`echo ${model_raw} | tr [A-Z] [a-z]`"
    ;;
esac

case "$model" in
  ppc750)  echo 'SD_SYSINFO_CPU_MODEL_PPC_750' ;;
  ppc7450) echo 'SD_SYSINFO_CPU_MODEL_PPC_7450' ;;
  *)       echo 'SD_SYSINFO_CPU_MODEL_UNKNOWN' ;;
esac
