#!/bin/sh

PROGRAM_NAME="sd-configpkg"

. ${SYSDEP_BASE_DIRECTORY}/sysdep-subs || exit 1

debug()
{
  SYSDEP_DEBUG "${PROGRAM_NAME}: $1"
}

if [ $# -ne 2 ]
then
  ${SYSDEP_UTIL_ECHO} "${PROGRAM_NAME}: usage: pkg flags"
  ${SYSDEP_UTIL_EXIT} 1
fi

PACKAGE_NAME="$1"
CONFIG_FLAGS="$2"

PATH_ELEMENTS=`${SYSDEP_UTIL_ECHO} "${PATH}" | ${SYSDEP_UTIL_TR} ':' ' '` ||
  SYSDEP_FATAL "${PROGRAM_NAME}: could not split PATH"

#
# Search in each element of ${PATH} and execute pkg-config binary using
# absolute path.
#

for DIR in ${PATH_ELEMENTS}
do
  if [ ! -x ${DIR}/pkg-config ]
  then
    debug "${DIR}/pkg-config not executable or nonexistent"
  else
    debug "executing ${DIR}/pkg-config ${CONFIG_FLAGS}"
    ${DIR}/pkg-config ${PACKAGE_NAME} ${CONFIG_FLAGS} 2>/dev/null
    RETURN_CODE=$?
    if [ ${RETURN_CODE} -eq 0 ]
    then
      debug "execution successful"
    else
      debug "execution failed"
    fi
    ${SYSDEP_UTIL_EXIT} $?
  fi
done

debug "could not locate or execute pkg-config"
${SYSDEP_UTIL_EXIT} 1
