#!/bin/sh

if [ x"$1" = x ]
then
  exit 1
fi

exec 2>/dev/null
sys="$1"
ncpu=0

case "$sys" in
  SYSDEP_OS_LINUX)
    ncpu=`grep -i '^processor' /proc/cpuinfo | wc -l`
    ;;
  *)
    ncpu="`sysctl hw.ncpu | awk '{print $2}'`"
    ;;
esac

echo "${ncpu}"
