#!/bin/sh

. ${SYSDEP_BASE_DIRECTORY}/sysdep-subs || exit 1

if [ $# -lt 3 ]
then
  ${SYSDEP_UTIL_ECHO} 'sd-configman: usage: file path prefix'
  ${SYSDEP_UTIL_EXIT} 111
fi

file="$1"
path="$2"
prefix="$3"

for path_element in ${path}
do
  if [ -f "${path_element}/${file}" ]
  then
    ${SYSDEP_UTIL_ECHO} "${prefix}${path_element} "
    ${SYSDEP_UTIL_EXIT} 0
  fi
done

${SYSDEP_UTIL_EXIT} 1
