#!/bin/sh

if [ $# -ne 1 ]
then
  echo "sd-run: usage: modules/module" 1>&2
  exit 1
fi

#
# Load essential subs.
#

. ./sysdep-subs "$1" || exit 1

#
# Load essential subroutines (not passed through shell executions).
#

. ./sysdep-boot "$1" || exit 1

#
# Clean standard files.
#

SDM_STANDARD_FILES="
  ${SYSDEP_BASE_DIRECTORY}/sd-cpuidx86
  ${SYSDEP_BASE_DIRECTORY}/sd-cpuidx86.lock
  ${SYSDEP_BASE_DIRECTORY}/sd-cpuidx86.o
  ${SYSDEP_BASE_DIRECTORY}/sd-cpuidx86.o.lock
  ${SYSDEP_BASE_DIRECTORY}/sd-arch
  ${SYSDEP_BASE_DIRECTORY}/sd-arch.lock
  ${SYSDEP_BASE_DIRECTORY}/sd-arch.o
  ${SYSDEP_BASE_DIRECTORY}/sd-arch.o.lock
  ${SYSDEP_BASE_DIRECTORY}/sd-cctype
  ${SYSDEP_BASE_DIRECTORY}/sd-cctype.lock
  ${SYSDEP_BASE_DIRECTORY}/sd-cctype.o
  ${SYSDEP_BASE_DIRECTORY}/sd-cctype.o.lock
  ${SYSDEP_BASE_DIRECTORY}/sd-ccversion
  ${SYSDEP_BASE_DIRECTORY}/sd-ccversion.lock
  ${SYSDEP_BASE_DIRECTORY}/sd-ccversion.o
  ${SYSDEP_BASE_DIRECTORY}/sd-ccversion.o.lock
  ${SYSDEP_BASE_DIRECTORY}/sd-adaversion.lock
  ${SYSDEP_BASE_DIRECTORY}/sd-adaversion.out
  ${SYSDEP_BASE_DIRECTORY}/sd-os
  ${SYSDEP_BASE_DIRECTORY}/sd-os.lock
  ${SYSDEP_BASE_DIRECTORY}/sd-os.o
  ${SYSDEP_BASE_DIRECTORY}/sd-os.o.lock
  ${SYSDEP_BASE_DIRECTORY}/sd-locker
  ${SYSDEP_BASE_DIRECTORY}/sd-locker.lock
  ${SYSDEP_BASE_DIRECTORY}/sd-locker.o
  ${SYSDEP_BASE_DIRECTORY}/sd-locker.o.lock
  ${SYSDEP_OUTPUT_DIRECTORY}/sysdeps.out"

for file in ${SDM_STANDARD_FILES}
do
  SYSDEP_REMOVE "${file}" || SYSDEP_FATAL "error removing standard files"
done

#
# Clean up module files.
#

cd "${SYSDEP_MODULE_PATH}" ||
  SYSDEP_FATAL "could not change directory to '${SYSDEP_MODULE_PATH}'"

SYSDEP_DEBUG "moved to ${SYSDEP_BASE_DIRECTORY}/${SYSDEP_MODULE_PATH}"

. ${SYSDEP_BASE_DIRECTORY}/sysdep-mod-clean || exit 1
