#!/bin/sh

if [ $# -ne 2 ]
then
  echo 'usage: file path prefix'
fi

file="$1"
path="$2"
prefix="$3"

for f in ${path}
do
  if [ -f "${f}/${file}" ]
  then
    echo "${prefix}${f} "
    return 0
  fi
done
return 1
