#!/bin/sh

. ${SYSDEP_BASE_DIRECTORY}/sysdep-subs || exit 1

warn()
{
  SYSDEP_DEBUG "sd-cpunum: $1"
}

if [ $# -ne 1 ]
then
  echo "sd-cpufreq: usage: os" 1>&2
  exit 1
fi

freq=0

sys="$1"
case "$sys" in
  SD_SYSINFO_OS_DARWIN)
    freq="`sysctl hw.cpufrequency | awk '{print $2}'`"
    let freq=freq/1000000
    ;;
  SD_SYSINFO_OS_DRAGONFLY)
    freq=`sysctl hw.tsc_frequency | awk '{print $NF}'`
    if [ $? -eq 0 ]
    then
      freq=`expr ${freq} / 1000000`
    fi
    ;;
  SD_SYSINFO_OS_FREEBSD)
    freq="`sysctl dev.cpu.0.freq | awk '{print $2}'`"
    ;; 
  SD_SYSINFO_OS_LINUX)
    freq="`grep -i 'cpu MHz' /proc/cpuinfo | awk '{print $NF}' | head -n 1`"
    ;;
  SD_SYSINFO_OS_VMS)
    freq="`SHOW CPU /FULL | grep Speed | awk '{print $2}' | head -1`"
    ;;
  SD_SYSINFO_OS_SUNOS)
    freq="`psrinfo -v 0 | grep MHz | tr -d 'A-Za-z,' | awk '{print $NF}'`"
    ;;
esac

if [ -z "${freq}" ]
then
  freq=0
fi

if [ $freq -eq 0 ]
then
  warn "CPU frequency detection failed - defaulting to 0"
  freq=0
fi

echo "$freq"
