#!/bin/sh

. ${SYSDEP_BASE_DIRECTORY}/sysdep-subs || exit 1

warn()
{
  SYSDEP_DEBUG "sd-cpunum: $1"
}

if [ $# -ne 1 ]
then
  echo "sd-cpunum: usage: os" 1>&2
  exit 1
fi

sys="$1"

case "$sys" in
  SD_SYSINFO_OS_LINUX)
    ncpu="`grep -i '^processor' /proc/cpuinfo | wc -l`"
    res=$?
    ;;
  SD_SYSINFO_OS_CRAY_UNICOS)
    ncpu="`getconf CRAY_NCPU`"
    res=$?
    ;;
  SD_SYSINFO_OS_IRIX)
    ncpu="`getconf NUM_PROCESSORS`"
    res=$?
    ;;
  SD_SYSINFO_OS_SUNOS)
    ncpu="`psrinfo | wc -l | tr -d ' '`"
    res=$?
    ;;
  SD_SYSINFO_OS_MS_WINDOWS)
    ncpu="${NUMBER_OF_PROCESSORS}"
    res=$?
    ;;
  SD_SYSINFO_OS_VMS)
    ncpu="`SHOW CPU /BRIEF | grep CPU | wc -l | tr -d ' '`"
    res=$?
    ;;
  SD_SYSINFO_OS_MINIX)
    ncpu=1
    res=0
    ;;
  SD_SYSINFO_OS_OPENBSD)
    ncpu="`sysctl hw.ncpu | awk -F= '{print $NF}'`"
    res=$?
    ;;
  *)
    ncpu=`sysctl hw.ncpu`
    res=$?

    if [ ${res} -eq 0 ]
    then
      ncpu="`echo ${ncpu} | awk '{print $NF}'`"
    else
      ncpu=0
    fi
    ;;
esac

if [ $res -ne 0 ]
then
  warn "CPU enumeration failed - number of CPUs defaulted to 0"
fi

echo "${ncpu}"
