#!/bin/sh

. ${SYSDEP_BASE_DIRECTORY}/sysdep-subs || exit 1

if [ $# -ne 1 ]
then
  echo "sd-cpuclinesz: usage: os" 1>&2
  exit 1
fi

cache=0

sys="$1"
case "$sys" in
  SD_SYSINFO_OS_DARWIN)
    cache_raw=`sysctl hw.cachelinesize 2>/dev/null`
    if [ $? -eq 0 ]
    then
      cache=`echo ${cache_raw} | awk '{print $NF}'`
    else
      cache_raw="`sysctl hw.cacheline 2>/dev/null`"
      if [ $? -eq 0 ]
      then
        cache=`echo ${cache_raw} | awk '{print $NF}'`
      fi
    fi
    ;; 
esac

if [ -f ${SYSDEP_BASE_DIRECTORY}/sd-cpuidx86 ]
then
  cache=`${SYSDEP_BASE_DIRECTORY}/sd-cpuidx86 cacheline 2>/dev/null`
fi

if [ ! -z "${cache}" ]
then
  echo "$cache"
else
  echo 0
fi
