#!/bin/sh

if [ -z ${SYSDEP_CC} ]
then
  SYSDEP_CC="cc"
fi

if [ x"$1" = x ]
then
  exit 1
fi

exec 2>/dev/null
sys="$1"
cache=0

case "$sys" in
  SYSDEP_OS_DARWIN)
    cache="`sysctl hw.l2cachesize | awk '{print $2}'`"
    ;; 
esac

if [ -f ./sd-cpuidx86 ]
then
  cache=`./sd-cpuidx86 l2cachesize`
fi

if [ -z "${cache}" ]
then
  echo 0
else
  echo "${cache}"
fi
