#!/bin/sh

if [ $# -ne 1 ]
then
  echo "sd-cpul1icache: usage: os" 1>&2
  exit 1
fi

sys="$1"
cache=0

case "$sys" in
  SD_SYSINFO_OS_DARWIN)
    cache="`sysctl hw.l1icachesize | awk '{print $2}'`"
    ;; 
esac

if [ -f ${SYSDEP_BASE_DIRECTORY}/sd-cpuidx86 ]
then
  cache=`${SYSDEP_BASE_DIRECTORY}/sd-cpuidx86 l1icachesize 2>/dev/null`
fi

if [ ! -z "${cache}" ]
then
  echo "$cache"
else
  echo 0
fi
