#!/bin/sh

if [ -z ${SYSDEP_CC} ]
then
  SYSDEP_CC="cc"
fi

if [ x"$1" = x ]
then
  exit 1
fi

exec 2>/dev/null
sys="$1"

case "$sys" in
  SYSDEP_OS_DARWIN)
    alti="`sysctl hw.optional.altivec | awk '{print $2}'`"
    if [ "${alti}" = "1" ]
    then
      echo '#define SYSDEP_HAVE_CPU_EXT_ALTIVEC'
    fi
    ;; 
esac

# try x86
${SYSDEP_CC} -o sd-cpuidx86 sd-cpuidx86.c
if [ $? -eq 0 ]
then
  f=`./sd-cpuidx86 mmx`
  if [ $f -eq 1 ]; then echo "#define SYSDEP_HAVE_CPU_EXT_MMX"; fi
  f=`./sd-cpuidx86 mmx2`
  if [ $f -eq 1 ]; then echo "#define SYSDEP_HAVE_CPU_EXT_MMX2"; fi
  f=`./sd-cpuidx86 3dnow`
  if [ $f -eq 1 ]; then echo "#define SYSDEP_HAVE_CPU_EXT_3DNOW"; fi
  f=`./sd-cpuidx86 3dnowext`
  if [ $f -eq 1 ]; then echo "#define SYSDEP_HAVE_CPU_EXT_3DNOWEXT"; fi
  f=`./sd-cpuidx86 sse`
  if [ $f -eq 1 ]; then echo "#define SYSDEP_HAVE_CPU_EXT_SSE"; fi
  f=`./sd-cpuidx86 sse2`
  if [ $f -eq 1 ]; then echo "#define SYSDEP_HAVE_CPU_EXT_SSE2"; fi
  f=`./sd-cpuidx86 sse3`
  if [ $f -eq 1 ]; then echo "#define SYSDEP_HAVE_CPU_EXT_SSE3"; fi
  f=`./sd-cpuidx86 sse4`
  if [ $f -eq 1 ]; then echo "#define SYSDEP_HAVE_CPU_EXT_SSE4"; fi
  rm -f sd-cpuidx86
fi
