#!/bin/sh

if [ $# -ne 1 ]
then
  echo "sd-cpuclinesz: usage: os" 1>&2
  exit 1
fi

cache=0

sys="$1"
case "$sys" in
  SD_SYSINFO_OS_DARWIN)
    cache="`sysctl hw.cacheline | awk '{print $2}'`"
    ;; 
esac

if [ -f ${SYSDEP_BASE_DIRECTORY}/sd-cpuidx86 ]
then
  cache=`${SYSDEP_BASE_DIRECTORY}/sd-cpuidx86 cacheline 2>/dev/null`
fi

if [ ! -z "${cache}" ]
then
  echo "$cache"
else
  echo 0
fi
