#!/bin/sh

. ${SYSDEP_BASE_DIRECTORY}/sysdep-subs || exit 1

FILE_PATH_DIRS="
${SYSDEP_OUTPUT_DIRECTORY}/
${SYSDEP_BASE_DIRECTORY}/
"

file_get_by_path()
{
  targ_file="$1"
  orig_text="$2"

  for dir in ${FILE_PATH_DIRS}
  do
    if [ -f "${dir}/${targ_file}" ]
    then
      tmp=`${SYSDEP_UTIL_HEAD} -n 1 "${dir}/${targ_file}"`
      if [ ! -z "${tmp}" ]
      then
        ${SYSDEP_UTIL_ECHO} "${tmp}"
        return 0
      fi
    fi
  done

  ${SYSDEP_UTIL_ECHO} "${orig_text}"
  return 1
}

file_exists_by_path()
{
  targ_file="$1"

  for dir in ${FILE_PATH_DIRS}
  do
    if [ -f "${dir}/${targ_file}" ]
    then
      return 1
    fi
  done

  return 0
}

file_show_by_path()
{
  targ_file="$1"

  for dir in ${FILE_PATH_DIRS}
  do
    if [ -f "${dir}/${targ_file}" ]
    then
      ${SYSDEP_UTIL_ECHO} "${dir}/${targ_file}"
      return 1
    fi
  done

  return 0
}

if [ $# -lt 2 ]
then
  ${SYSDEP_UTIL_ECHO} "sd-file: usage: command file [...]"
  ${SYSDEP_UTIL_EXIT} 1
fi

command=$1
file=$2
origtext=$3

case "${command}" in
  get)
    file_get_by_path "${file}" "${origtext}"
    ${SYSDEP_UTIL_EXIT} $?
    ;;
  exists)
    file_exists_by_path "${file}"
    ${SYSDEP_UTIL_EXIT} $?
    ;;
  show)
    file_show_by_path "${file}"
    ${SYSDEP_UTIL_EXIT} $?
    ;;
  *)
    ${SYSDEP_UTIL_ECHO} '${SYSDEP_MODULE}: fatal: unknown command'
    ${SYSDEP_UTIL_EXIT} 1
    ;;
esac
