#!/bin/sh

if [ $# -ne 1 ]
then
  echo "sd-cpufeat: usage: os" 1>&2
  exit 1
fi

sys="$1"

case "$sys" in
  SD_SYSINFO_OS_IRIX)
    ver=`uname -R | awk '{print $NF}'`
    ;;
  SD_SYSINFO_OS_SUNOS)
    ver=`uname -r`-`uname -v`
    ;;
  SD_SYSINFO_OS_VMS)
    ver=`uname -v`
    ;;
  SD_SYSINFO_OS_MS_WINDOWS)
    ver=`uname -s | awk -F- '{print $NF}'`
    ;;
  SD_SYSINFO_OS_MINIX)
    ver_r=`uname -r`
    ver_v=`uname -v | tr -d [a-z]`
    ver="${ver_r}.${ver_v}"
    ;;
  *)
    ver=`uname -r`
    if [ $? -ne 0 ]
    then
      ver=0.0
    fi
    ;;
esac
echo ${ver} | tr '/:[A-Z]' '..[a-z]'
