#!/bin/sh

exec 2>/dev/null

sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
case "$sys" in
  bsd.os) echo 'SYSDEP_OS_BSDOS' ;;
  freebsd) echo 'SYSDEP_OS_FREEBSD' ;;
  netbsd) echo 'SYSDEP_OS_NETBSD';;
  openbsd) echo 'SYSDEP_OS_OPENBSD';;
  darwin) echo 'SYSDEP_OS_DARWIN';;
  linux) echo 'SYSDEP_OS_LINUX';;
  aix) echo 'SYSDEP_OS_AIX';;
  sunos) echo 'SYSDEP_OS_SUNOS';;
  unix_sv) echo 'SYSDEP_OS_UNIX_SV';;
  hp-ux) echo 'SYSDEP_OS_HPUX';;
  *) echo 'SYSDEP_OS_UNKNOWN';;
esac
