#!/bin/sh

#
# Essential subprograms.
#

SYSDEP_FATAL()
{
  if [ ! -z "${SYSDEP_MODULE}" ]
  then
    echo "${SYSDEP_MODULE}: fatal: $1" 1>&2
  else
    echo "sysdep-main: fatal: $1" 1>&2
  fi
  exit 1
}

SYSDEP_ERROR()
{
  if [ ! -z "${SYSDEP_MODULE}" ]
  then
    echo "${SYSDEP_MODULE}: error: $1" 1>&2
  else
    echo "sysdep-main: error: $1" 1>&2
  fi
}

SYSDEP_INFO()
{
  if [ ! -z "${SYSDEP_MODULE}" ]
  then
    echo "${SYSDEP_MODULE}: info: $1" 1>&2
  else
    echo "sysdep-main: info: $1" 1>&2
  fi
}

SYSDEP_DEBUG()
{
  if [ -f "${SYSDEP_BASE_DIRECTORY}/conf-debug" ]
  then
    if [ ! -z "${SYSDEP_MODULE}" ]
    then
      echo "${SYSDEP_MODULE}: debug: $1" 1>&2
    else
      echo "sysdep-main: debug: $1" 1>&2
    fi
  fi
}

SYSDEP_REMOVE()
{
  SYSDEP_DEBUG "remove $@"
  rm -f $@
  return $?
}

SYSDEP_MOVE()
{
  SYSDEP_DEBUG "move $1 $2"
  mv -f "$1" "$2"
  return $?
}
