#!/bin/sh

#
# this file is only ever called by modules, so all paths must be
# relative to the module ("../../").
#

# path from module to sysdeps dir (MUST end with trailing slash)
SYSDEP_DIR_RELATIVE="../../"
export SYSDEP_DIR_RELATIVE

# outdir is relative to each entry in modules directory, can be
SYSDEP_OUTDIR="${SYSDEP_DIR_RELATIVE}/../"

# override with conf-outdir if it exists
if [ -f "${SYSDEP_DIR_RELATIVE}/conf-outdir" ]
then
  DIR=`head -n 1 "${SYSDEP_DIR_RELATIVE}/conf-outdir"`
  if [ $? -eq 0 ]
  then
    SYSDEP_OUTDIR="${SYSDEP_DIR_RELATIVE}/${DIR}"
  fi
fi
export SYSDEP_OUTDIR

SYSDEP_TRY_CONFIG_BIN=${SYSDEP_DIR_RELATIVE}/sd-configbin
SYSDEP_TRY_PKG_CONFIG=${SYSDEP_DIR_RELATIVE}/sd-configpkg
SYSDEP_TRY_MANUAL=${SYSDEP_DIR_RELATIVE}/sd-configman
SYSDEP_ERROR=${SYSDEP_DIR_RELATIVE}/sd-error

export SYSDEP_TRY_CONFIG_BIN
export SYSDEP_TRY_PKG_CONFIG
export SYSDEP_TRY_MANUAL
export SYSDEP_ERROR

# 'clean' scripts may set this variable to vastly speed up 'make clean'
if [ -z "${SYSDEP_CLEAN}" ];
then
  . ${SYSDEP_DIR_RELATIVE}/sysdep-subs;
else
  rm -f ${SYSDEP_DIR_RELATIVE}/sd-cpuidx86 \
        ${SYSDEP_DIR_RELATIVE}/sd-cpuidx86.o
  rm -f ${SYSDEP_DIR_RELATIVE}/sd-arch \
        ${SYSDEP_DIR_RELATIVE}/sd-arch.o
  rm -f ${SYSDEP_DIR_RELATIVE}/sd-cctype \
        ${SYSDEP_DIR_RELATIVE}/sd-cctype.o
  rm -f ${SYSDEP_DIR_RELATIVE}/sd-ccversion \
        ${SYSDEP_DIR_RELATIVE}/sd-ccversion.o
  rm -f ${SYSDEP_DIR_RELATIVE}/sd-os \
        ${SYSDEP_DIR_RELATIVE}/sd-os.o
fi
