#!/bin/sh

#
# This file is intended to be called by 'sysdeps-main'
#
# This file operates under the protection of a global lock, due to
# compiling and using binaries in the working directory.
#

#
# Read configuration files, compiling support programs if necessary.
#

if [ ${SYSDEP_CROSS_COMPILE} -eq 0 ]
then
  if [ ! -x ${SYSDEP_DIR_RELATIVE}/sd-cpuidx86 ]
  then
    SYSDEP_DEBUG "compiling sd-cpuidx86"
    ${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o ${SYSDEP_DIR_RELATIVE}/sd-cpuidx86.o \
    ${SYSDEP_DIR_RELATIVE}/sd-cpuidx86.c 2>/dev/null
    ${SYSDEP_LD} ${SYSDEP_LDFLAGS} -o ${SYSDEP_DIR_RELATIVE}/sd-cpuidx86 \
    ${SYSDEP_DIR_RELATIVE}/sd-cpuidx86.o 2>/dev/null
  fi
  if [ ! -x ${SYSDEP_DIR_RELATIVE}/sd-arch ]
  then
    SYSDEP_DEBUG "compiling sd-arch"
    ${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o ${SYSDEP_DIR_RELATIVE}/sd-arch.o \
    ${SYSDEP_DIR_RELATIVE}/sd-arch.c || SYSDEP_ERROR "sd-arch failed to compile"
    ${SYSDEP_LD} ${SYSDEP_LDFLAGS} -o ${SYSDEP_DIR_RELATIVE}/sd-arch \
    ${SYSDEP_DIR_RELATIVE}/sd-arch.o || SYSDEP_ERROR "sd-arch failed to link"
  fi
  if [ ! -x ${SYSDEP_DIR_RELATIVE}/sd-cctype ]
  then
    SYSDEP_DEBUG "compiling sd-cctype"
    ${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o ${SYSDEP_DIR_RELATIVE}/sd-cctype.o \
    ${SYSDEP_DIR_RELATIVE}/sd-cctype.c || SYSDEP_ERROR "sd-cctype failed to compile"
    ${SYSDEP_LD} ${SYSDEP_LDFLAGS} -o ${SYSDEP_DIR_RELATIVE}/sd-cctype \
    ${SYSDEP_DIR_RELATIVE}/sd-cctype.o || SYSDEP_ERROR "sd-cctype failed to link"
  fi
  if [ ! -x ${SYSDEP_DIR_RELATIVE}/sd-os ]
  then
    SYSDEP_DEBUG "compiling sd-os"
    ${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o ${SYSDEP_DIR_RELATIVE}/sd-os.o \
    ${SYSDEP_DIR_RELATIVE}/sd-os.c || SYSDEP_ERROR "sd-os failed to compile"
    ${SYSDEP_LD} ${SYSDEP_LDFLAGS} -o ${SYSDEP_DIR_RELATIVE}/sd-os \
    ${SYSDEP_DIR_RELATIVE}/sd-os.o || SYSDEP_ERROR "sd-os failed to link"
  fi
  if [ ! -x ${SYSDEP_DIR_RELATIVE}/sd-ccversion ]
  then
    SYSDEP_DEBUG "compiling sd-ccversion"
    ${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o ${SYSDEP_DIR_RELATIVE}/sd-ccversion.o \
    ${SYSDEP_DIR_RELATIVE}/sd-ccversion.c || SYSDEP_ERROR "sd-ccversion failed to compile"
    ${SYSDEP_LD} ${SYSDEP_LDFLAGS} -o ${SYSDEP_DIR_RELATIVE}/sd-ccversion \
    ${SYSDEP_DIR_RELATIVE}/sd-ccversion.o || SYSDEP_ERROR "sd-ccversion failed to link"
  fi

  # Find system type.
  SYSDEP_OS="`${SYSDEP_DIR_RELATIVE}/sd-os`" ||
    SYSDEP_ERROR "sd-os failed - operating system will be marked 'unknown'"
  export SYSDEP_OS
  
  # Find system version.
  SYSDEP_OSVERSION="`${SYSDEP_DIR_RELATIVE}/sd-osversion ${SYSDEP_OS}`" ||
    SYSDEP_ERROR "sd-osversion failed - operating system version will be marked '0.0.0'"
  export SYSDEP_OSVERSION
  
  # Find system architecture.
  SYSDEP_ARCH="`${SYSDEP_DIR_RELATIVE}/sd-arch`" ||
    SYSDEP_ERROR "sd-arch failed - architecture will be marked 'unknown'"
  export SYSDEP_ARCH
  
  # Find compiler type.
  SYSDEP_CCTYPE="`${SYSDEP_DIR_RELATIVE}/sd-cctype`" ||
    SYSDEP_ERROR "sd-cctype failed - compiler type will be marked 'unknown'"
  export SYSDEP_CCTYPE
  
  # Find compiler version.
  SYSDEP_CCVERSION="`${SYSDEP_DIR_RELATIVE}/sd-ccversion`" ||
    SYSDEP_ERROR "sd-ccversion failed - compiler version will be marked '0.0.0'"
  export SYSDEP_CCVERSION
  
  # Find CPU features (Altivec, SSE etc).
  SYSDEP_CPU_EXT="`${SYSDEP_DIR_RELATIVE}/sd-cpufeat ${SYSDEP_OS}`" ||
    SYSDEP_ERROR "sd-cpufeat failed - CPU will appear to have no features"
  export SYSDEP_CPU_EXT
  
  # Find number of CPUs.
  SYSDEP_CPU_NUM="`${SYSDEP_DIR_RELATIVE}/sd-cpunum ${SYSDEP_OS}`" ||
    SYSDEP_ERROR "sd-cpunum failed - number of CPUs will be zero"
  export SYSDEP_CPU_NUM
  
  # Find CPU model.
  SYSDEP_CPU_MODEL="`${SYSDEP_DIR_RELATIVE}/sd-cpumodel ${SYSDEP_OS}`" ||
    SYSDEP_ERROR "sd-cpumodel failed - CPU model will be marked 'unknown'"
  export SYSDEP_CPU_MODEL
  
  # Find CPU frequency.
  SYSDEP_CPU_FREQ="`${SYSDEP_DIR_RELATIVE}/sd-cpufreq ${SYSDEP_OS}`" ||
    SYSDEP_ERROR "sd-cpufreq failed - CPU frequency will be zero"
  export SYSDEP_CPU_FREQ
  
  # Find CPU L1 instruction cache size.
  SYSDEP_CPU_L1_INST_CACHE_SIZE="`${SYSDEP_DIR_RELATIVE}/sd-cpul1icache ${SYSDEP_OS}`" ||
    SYSDEP_ERROR "sd-cpul1icache failed - L1 instruction cache size will be zero"
  export SYSDEP_CPU_L1_INST_CACHE_SIZE
  
  # Find CPU L1 data cache size.
  SYSDEP_CPU_L1_DATA_CACHE_SIZE="`${SYSDEP_DIR_RELATIVE}/sd-cpul1dcache ${SYSDEP_OS}`" ||
    SYSDEP_ERROR "sd-cpul1dcache failed - L1 data cache size will be zero"
  export SYSDEP_CPU_L1_DATA_CACHE_SIZE
  
  # Find CPU L2 cache size.
  SYSDEP_CPU_L2_CACHE_SIZE="`${SYSDEP_DIR_RELATIVE}/sd-cpul2cache ${SYSDEP_OS}`" ||
    SYSDEP_ERROR "sd-cpul12cache failed - L2 cache size will be zero"
  export SYSDEP_CPU_L2_CACHE_SIZE
  
  # Find CPU L3 cache size.
  SYSDEP_CPU_L3_CACHE_SIZE="`${SYSDEP_DIR_RELATIVE}/sd-cpul3cache ${SYSDEP_OS}`" ||
    SYSDEP_ERROR "sd-cpul13cache failed - L3 cache size will be zero"
  export SYSDEP_CPU_L3_CACHE_SIZE
  
  # Find CPU cache line size.
  SYSDEP_CPU_CACHE_LINE_SIZE="`${SYSDEP_DIR_RELATIVE}/sd-cpuclinesz ${SYSDEP_OS}`" ||
    SYSDEP_ERROR "sd-cpuclinesz failed - cache line size will be zero"
  export SYSDEP_CPU_CACHE_LINE_SIZE

  #----------------------------------------------------------------------
  # optional Ada components

  SYSDEP_ADA_TYPE="UNKNOWN"
  SYSDEP_ADA_VERSION="0.0.0"

  if [ "${SYSDEP_ADA_COMP}" ]
  then
    if [ ! -f "${SYSDEP_DIR_RELATIVE}/sd-adaversion.out" ]
    then
      SYSDEP_ADA_VERSION_TMP="`${SYSDEP_DIR_RELATIVE}/sd-adaversion \
        "${SYSDEP_ADA_COMP}"    \
        "${SYSDEP_ADA_CFLAGS}"  \
        "${SYSDEP_ADA_BIND}"    \
        "${SYSDEP_ADA_BFLAGS}"  \
        "${SYSDEP_ADA_LINK}"    \
        "${SYSDEP_ADA_LDFLAGS}"`"
      SYSDEP_ADA_TYPE=`echo "${SYSDEP_ADA_VERSION_TMP}" | awk '{print $1}'`
      SYSDEP_ADA_VERSION=`echo "${SYSDEP_ADA_VERSION_TMP}" | awk '{print $2}'`
      echo "${SYSDEP_ADA_VERSION_TMP}" > "${SYSDEP_DIR_RELATIVE}/sd-adaversion.out"
    else
      SYSDEP_ADA_TYPE=`cat "${SYSDEP_DIR_RELATIVE}/sd-adaversion.out" | awk '{print $1}'`
      SYSDEP_ADA_VERSION=`cat "${SYSDEP_DIR_RELATIVE}/sd-adaversion.out" | awk '{print $2}'`
    fi
  fi

  export SYSDEP_ADA_TYPE
  export SYSDEP_ADA_VERSION

else
  # find system type
  SYSDEP_OS="SYSDEP_OS_`${SYSDEP_FILE} get "conf-x-systype" "UNKNOWN"`"
  export SYSDEP_OS
  
  # find system version
  SYSDEP_OSVERSION=`${SYSDEP_FILE} get "conf-x-sysver" "0.0"`
  export SYSDEP_OSVERSION
  
  # find system architecture
  SYSDEP_ARCH="SYSDEP_ARCH_`${SYSDEP_FILE} get "conf-x-arch" "UNKNOWN"`"
  export SYSDEP_ARCH
  
  # find compiler type
  SYSDEP_CCTYPE="SYSDEP_CCTYPE_`${SYSDEP_FILE} get "conf-x-cctype" "UNKNOWN"`"
  export SYSDEP_CCTYPE
  
  # find compiler version
  SYSDEP_CCVERSION=`${SYSDEP_FILE} get "conf-x-ccver" "0.0.0"`
  export SYSDEP_CCVERSION
  
  # find cpu features
  SYSDEP_CPU_EXT=`${SYSDEP_FILE} get "conf-x-cpufeat" ""`
  export SYSDEP_CPU_EXT
  
  # find number of CPUs
  SYSDEP_CPU_NUM=`${SYSDEP_FILE} get "conf-x-cpunum" "0"`
  export SYSDEP_CPU_NUM
  
  # find CPU model
  SYSDEP_CPU_MODEL=`${SYSDEP_FILE} get "conf-x-cpumodel" ""`
  export SYSDEP_CPU_MODEL
  
  # find CPU frequency
  SYSDEP_CPU_FREQ=`${SYSDEP_FILE} get "conf-x-cpufreq" "0"`
  export SYSDEP_CPU_FREQ
  
  # find CPU L1 instruction cache size
  SYSDEP_CPU_L1_INST_CACHE_SIZE=`${SYSDEP_FILE} get "conf-x-cpul1ic" "0"`
  export SYSDEP_CPU_L1_INST_CACHE_SIZE
  
  # find CPU L1 data cache size
  SYSDEP_CPU_L1_DATA_CACHE_SIZE=`${SYSDEP_FILE} get "conf-x-cpul1dc" "0"`
  export SYSDEP_CPU_L1_DATA_CACHE_SIZE
  
  # find CPU L2 cache size
  SYSDEP_CPU_L2_CACHE_SIZE=`${SYSDEP_FILE} get "conf-x-cpul2c" "0"`
  export SYSDEP_CPU_L2_CACHE_SIZE
  
  # find CPU L3 cache size
  SYSDEP_CPU_L3_CACHE_SIZE=`${SYSDEP_FILE} get "conf-x-cpul3c" "0"`
  export SYSDEP_CPU_L3_CACHE_SIZE
  
  # find CPU cache line size
  SYSDEP_CPU_CACHE_LINE_SIZE=`${SYSDEP_FILE} get "conf-x-cpucline" "0"`
  export SYSDEP_CPU_CACHE_LINE_SIZE

  #
  # optional Ada components
  #

  # find compiler type
  SYSDEP_ADA_TYPE="SYSDEP_ADA_TYPE_`${SYSDEP_FILE} get "conf-x-adatype" "UNKNOWN"`"
  export SYSDEP_ADA_TYPE
  
  # find compiler version
  SYSDEP_ADA_VERSION=`${SYSDEP_FILE} get "conf-x-adaver" "0.0.0"`
  export SYSDEP_ADA_VERSION
fi

# Override path prefix.
PREFIX=`${SYSDEP_FILE} get "conf-prefix" ""`
for dir in ${PREFIX}
do
  ${SYSDEP_INFO} "using custom prefix ${dir}/include"
  ${SYSDEP_INFO} "using custom prefix ${dir}/lib"
  STDINC_ADD="${STDINC_ADD} ${dir}/include"
  STDLIB_ADD="${STDLIB_ADD} ${dir}/lib"
done

# Override path prefix for cross compilation.
if [ ${SYSDEP_CROSS_COMPILE} -eq 1 ]
then
  PREFIX=`${SYSDEP_FILE} get "conf-x-prefix" ""`
  for dir in ${PREFIX}
  do
    ${SYSDEP_INFO} "using custom x-prefix ${dir}/include"
    ${SYSDEP_INFO} "using custom x-prefix ${dir}/lib"
    STDINC_ADD="${STDINC_ADD} ${dir}/include"
    STDLIB_ADD="${STDLIB_ADD} ${dir}/lib"
  done
fi

# Standard include path.
SYSDEP_STDINC="/usr/include /usr/local/include"
case ${SYSDEP_OS} in
  SYSDEP_OS_DARWIN) SYSDEP_STDINC="/opt/local/include /opt/include /sw/include ${SYSDEP_STDINC}";;
  SYSDEP_OS_SUNOS) SYSDEP_STDINC="/opt/csw/include /usr/sfw/include ${SYSDEP_STDINC}";;
  *)
esac
SYSDEP_STDINC="${STDINC_ADD} ${SYSDEP_STDINC}"
export SYSDEP_STDINC

# Standard library path.
SYSDEP_STDLIB="/usr/lib /usr/local/lib"
case ${SYSDEP_OS} in
  SYSDEP_OS_DARWIN) SYSDEP_STDLIB="/opt/local/lib /opt/lib /sw/lib ${SYSDEP_STDLIB}";;
  SYSDEP_OS_SUNOS) SYSDEP_STDLIB="/opt/csw/lib /usr/sfw/lib ${SYSDEP_STDLIB}";;
  *)
esac
SYSDEP_STDLIB="${STDLIB_ADD} ${SYSDEP_STDLIB}"
export SYSDEP_STDLIB

# find system dynamic library suffix
SYSDEP_LIBSUFFIX="so"
case ${SYSDEP_OS} in
  SYSDEP_OS_DARWIN) SYSDEP_LIBSUFFIX="dylib" ;;
  SYSDEP_OS_HPUX) SYSDEP_LIBSUFFIX="sl";;
  SYSDEP_OS_MS_WINDOWS) SYSDEP_LIBSUFFIX="dll";;
  *) ;;
esac
export SYSDEP_LIBSUFFIX
