#!/bin/sh

sd_tmp="sysdeps.out"
f1_tmp="_float32.h"
f2_tmp="_float64.h"
echo "SYSDEPS floats clean ${f1_tmp}"

outdir="`head -n 1 ../conf-outdir`"
if [ -z "${outdir}" ]
then
  echo "fatal: outdir not defined" 2>&1
  exit 1
fi
outdir="../${outdir}"
f1_out="${outdir}/${f1_tmp}"
f2_out="${outdir}/${f2_tmp}"

rm -f ${f1_tmp} ${f2_tmp} ${f1_out} ${f2_out} ${sd_tmp}
