#!/bin/sh

fatal()
{
  echo "fatal: $1" 1>&2
  exit 1
}

temp32="$1"
temp64="$2"
tempsys="$3"

cc -o float32_make float32_make.c
if [ $? -ne 0 ]; then fatal "error compiling float32_make"; fi
cc -o float64_make float64_make.c
if [ $? -ne 0 ]; then fatal "error compiling float64_make"; fi

./float32_make 1>${temp32} 2>>${tempsys}
if [ $? -ne 0 ]; then fatal "could not get 32-bit floats"; fi
./float64_make 1>${temp64} 2>>${tempsys}
if [ $? -ne 0 ]; then fatal "could not get 64-bit floats"; fi

exit 0
