#!/bin/sh

sd_tmp="sysdeps.out"
f1_tmp="_float32.h"
f2_tmp="_float64.h"
echo "SYSDEPS floats run create ${f1_tmp} ${f2_tmp}"

outdir="`head -n 1 ../conf-outdir`"
if [ -z "${outdir}" ]
then
  echo "fatal: outdir not defined" 2>&1
  exit 1
fi
outdir="../${outdir}"
sd_out="${outdir}/${sd_tmp}"
f1_out="${outdir}/${f1_tmp}"
f2_out="${outdir}/${f2_tmp}"

./floats ${f1_tmp} ${f2_tmp} ${sd_tmp}
if [ $? -eq 0 ]
then
  cp ${f1_tmp} ${f1_out}
  cp ${f2_tmp} ${f2_out}
  cat ${sd_tmp} >> ${sd_out}
else
  exit 1
fi
