#!/bin/sh

exec 1> "$1"

path="${SYSDEP_STDLIB}"
lib="libfltk2.${SYSDEP_LIBSUFFIX}"

FLAGS=`${SYSDEP_TRY_CONFIG_BIN} "fltk2-config" "--ldflags --use-images"
2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS}
  exit 0
else
  ${SYSDEP_ERROR} "config binary failed"
fi

FLAGS=`${SYSDEP_TRY_PKG_CONFIG} "${pkg}" "--libs" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS}
  exit 0
else
  ${SYSDEP_ERROR} "pkg-config failed"
fi

FLAGS=`${SYSDEP_TRY_MANUAL} "${lib}" "${path}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS}
  exit 0
else
  ${SYSDEP_ERROR} "manual search failed"
fi

exit 0
