#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="libs-posix_rt"
f2_tmp="flags-posix_rt"
f3_tmp="_sd_posix_rt.h"
sd_tmp="sysdeps.out"
echo "SYSDEPS sd-posix_rt run create ${f1_tmp} ${f2_tmp} ${f3_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"
f2_out="${SYSDEP_OUTDIR}/${f2_tmp}"
f3_out="${SYSDEP_OUTDIR}/${f3_tmp}"
sd_out="${SYSDEP_OUTDIR}/${sd_tmp}"

./sd-posix_rt ${f1_tmp} ${f2_tmp} ${f3_tmp} ${sd_tmp}
cp ${f1_tmp} ${f1_out}
cp ${f2_tmp} ${f2_out}
cp ${f3_tmp} ${f3_out}
cat ${sd_tmp} >> ${sd_out}
