#!/bin/sh

SYSDEP_MODULE="pdcgi-flags"
export SYSDEP_MODULE

. ../../sysdep-main
if [ $? -ne 0 ]; then exit 111; fi

f1_tmp="`${SYSDEP_LINE} 1 < CREATES`"
f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

./pdcgi-flags ${f1_tmp}
cp ${f1_tmp} ${f1_out}
