#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="flags-sdl-mixer"
echo "SYSDEPS sdl-mixer-flags clean ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

rm -f ${f1_tmp} ${f1_out}
