#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

sd_tmp="sysdeps.out"
f1_tmp="_floatcast.h"
f2_tmp="libs-floatcast"
echo "SYSDEPS floatcast run create ${f1_tmp} ${f2_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"
f2_out="${SYSDEP_OUTDIR}/${f2_tmp}"
sd_out="${SYSDEP_OUTDIR}/${sd_tmp}"

./floatcast ${f1_tmp} ${f2_tmp} ${sd_tmp}
cp ${f1_tmp} ${f1_out}
cp ${f2_tmp} ${f2_out}
cat ${sd_tmp} >> ${sd_out}
