#!/bin/sh

SYSDEP_CLEAN=1
. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="libs-fastcgi"
echo "SYSDEPS fastcgi-libs clean ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"
rm -f ${f1_tmp} ${f1_out}
