#!/bin/sh

exec 1> "$1"

path="${SYSDEP_STDLIB}"
pkg="fcgi"
lib="lib${pkg}.${SYSDEP_LIBSUFFIX}"

FLAGS=`${SYSDEP_TRY_MANUAL} "${lib}" "${path}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} "-l${pkg}"
  exit 0
else
  ${SYSDEP_ERROR} "manual config failed"
fi

exit 0
