#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="_opengl_obj.c"
sd_tmp="sysdeps.out"
echo "SYSDEPS opengl-obj run create ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"
sd_out="${SYSDEP_OUTDIR}/${sd_tmp}"

./opengl-obj ${f1_tmp} ${sd_tmp}
cp ${f1_tmp} ${f1_out}
cat ${sd_tmp} >> ${sd_out}
