#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

finish()
{
  cat >> "${fout}" <<EOF
#endif
EOF
  echo "sysinfo: ${sysinfo}" >> ${sysdeps}
  exit 0
}

fout="$1"
sysdeps="$2"

oper="`./sys-os.sh`"
arch="`./cpu-arch.sh ${oper}`"
ncpu="`./cpu-num.sh ${oper}`"
mdel="`./cpu-model.sh ${oper}`"
feat="`./cpu-feat.sh ${oper}`"
freq="`./cpu-freq.sh ${oper}`"
l1ic="`./cpu-l1icache.sh ${oper}`"
l1dc="`./cpu-l1dcache.sh ${oper}`"
l2c="`./cpu-l2cache.sh ${oper}`"
l3c="`./cpu-l3cache.sh ${oper}`"
lsz="`./cpu-linesz.sh ${oper}`"

cat >> "${fout}" <<EOF
#ifndef _SYSINFO_H
#define _SYSINFO_H

#define SYSINFO_OS ${oper}
#define SYSINFO_ARCH ${arch}

#define SYSINFO_NCPUS ${ncpu}
#define SYSINFO_CPU_MODEL ${mdel}
#define SYSINFO_CPU_EXT ${feat}
#define SYSINFO_CPU_L1_INST_CACHE_SIZE ${l1ic}
#define SYSINFO_CPU_L1_DATA_CACHE_SIZE ${l1dc}
#define SYSINFO_CPU_L2_CACHE_SIZE ${l2c}
#define SYSINFO_CPU_L3_CACHE_SIZE ${l3c}
#define SYSINFO_CPU_CACHE_LINE_SIZE ${lsz}
#define SYSINFO_CPU_FREQ ${freq}

`./cpu-hasfeat.sh ${oper}`

EOF

finish
