#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

finish()
{
  cat >> "${fout}" <<EOF
#endif
EOF
  echo "sysinfo: ${sysinfo}" >> ${sysdeps}
  exit 0
}

fout="$1"
sysdeps="$2"

oper="`./sys-os.sh`"
arch="`./cpu-arch.sh ${oper}`"
ncpu="`./cpu-num.sh ${oper}`"
mdel="`./cpu-model.sh ${oper}`"
feat="`./cpu-feat.sh ${oper}`"

l1c="`./cpu-l1cache.sh ${oper}`"
l2c="`./cpu-l2cache.sh ${oper}`"
l3c="`./cpu-l3cache.sh ${oper}`"

cat >> "${fout}" <<EOF
#ifndef _SYSINFO_H
#define _SYSINFO_H

#define SYSINFO_OS ${oper}
#define SYSINFO_ARCH ${arch}

#define SYSINFO_NCPUS ${ncpu}
#define SYSINFO_CPU_MODEL ${mdel}
#define SYSINFO_CPU_EXT ${feat}
#define SYSINFO_CPU_L1_CACHE_SIZE ${l1c}
#define SYSINFO_CPU_L2_CACHE_SIZE ${l2c}
#define SYSINFO_CPU_L3_CACHE_SIZE ${l3c}

EOF

finish
