#!/bin/sh

fout="$1"

echo ${SYSDEP_CPU_EXT} | grep 'SYSDEP_CPU_EXT_SSE2' 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  case ${SYSDEP_CCTYPE} in
    SYSDEP_CCTYPE_GCC) echo '-msse2' > ${fout};;
    SYSDEP_CCTYPE_INTEL) echo '-msse2' > ${fout};;
  esac
else
  echo > ${fout}
fi
