#!/bin/sh

exec 1> "$1"

FLAGS=`${SYSDEP_TRY_CONFIG_BIN} "integer-conf" "compile slibdir ldflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS}
  exit 0
else
  ${SYSDEP_ERROR} "config binary failed"
fi

exit 0
