#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

exec 1> "$1"

args=""
path="${SYSDEP_STDLIB}"
lib="libSDLmain.a"

case ${SYSDEP_SYSTYPE} in
  darwin)
    lib="SDL"               # searching for framework
    args="-bind_at_load"    # darwin linker bug
    args="${args} -framework SDL -framework Cocoa -framework OpenGL
-lobjc"
    path="${path} /Library/Frameworks/SDL.framework"
    ;;
  *)
    ;;
esac

# freebsd workaround for versioned sdl-config
FLAGS=`try_config_bin "sdl12-config" "--libs" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${args}
  exit 0
fi
FLAGS=`try_config_bin "sdl11-config" "--libs" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${args}
  exit 0
fi
FLAGS=`try_config_bin "sdl-config" "--libs" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${args}
  exit 0
fi
error "try_config_bin failed"

FLAGS=`try_pkg_config "${pkg}" "--libs" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${args}
  exit 0
else
  error "try_pkg_config failed"
fi

FLAGS=`try_manual_search "${lib}" "${path}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  case ${SYSDEP_SYSTYPE} in
    darwin)
      echo ${args}
      exit 0
      ;;
    *)
      echo ${FLAGS} ${args}
      exit 0
      ;;
    esac
else
  error "try_manual_search failed"
fi

exit 0
