#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

exec 1> "$1"

args=""
path="${SYSDEP_STDLIB}"
lib="libSDLmain.a"

case ${SYSDEP_SYSTYPE} in
  sunos)
    path="${path} /usr/sfw/lib"
    ;;
  darwin)
    args="-bind_at_load"    # darwin linker bug
    path="/sw/lib ${path}"
    ;;
  *)
    ;;
esac

FLAGS=`try_config_bin "sdl-config" "--libs" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${args}
  exit 0
else
  error "try_config_bin failed"
fi

FLAGS=`try_pkg_config "${pkg}" "--libs" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${args}
  exit 0
else
  error "try_pkg_config failed"
fi

FLAGS=`try_manual_search "${lib}" "${path}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${args}
  exit 0
else
  error "try_manual_search failed"
fi

exit 0
