#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

search="NO"
path="/usr/local/lib"
lib="libSDLmain.a"

sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
if [ x"$sys" != x ]
then
  case "$sys" in
  darwin)
    path="/sw/lib ${path}"
    args="-framework SDL -framework Cocoa -framework OpenGL"
    search="YES"
    ;;
  *)
    ;;
  esac
fi

if [ "${search}" = "YES" ]
then
  search_lib "${lib}" "${path}" "${args}"
  if [ $? -ne 0 ]
  then
    fatal "could not locate ${lib}"
  fi
  exit 0
fi

# fall-through generic platform
str="`sdl-config --libs`"
if [ $? -ne 0 ]
then
  fatal "error running sdl-config"
fi

echo ${str}
