#!/bin/sh

fout="$1"
sysdeps="$2"

cat >> "${fout}" <<EOF
#ifndef _IOMECH_H
#define _IOMECH_H
EOF

cc -o trykqueue trykqueue.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#define HAVE_KQUEUE 1' >> "${fout}" 
  mechs="${mechs} kqueue"
fi

cc -o tryepoll tryepoll.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#define HAVE_EPOLL 1' >> "${fout}"
  mechs="${mechs} epoll"
fi

cc -o trypoll trypoll.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#define HAVE_POLL 1' >> "${fout}"
  mechs="${mechs} poll"
fi

cc -o tryselect1 tryselect1.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#define HAVE_SELECT 1' >> "${fout}"
  mechs="${mechs} select"
else
  cc -o tryselect2 tryselect2.c >/dev/null 2>&1
  if [ $? -eq 0 ]
  then
    echo '#define HAVE_SELECT 1' >> "${fout}"
    echo '#define SELECT_NEEDS_TIME_H' >> "${fout}" # hp-ux
    mechs="${mechs} select"
  fi
fi

cat >> "${fout}" <<EOF
#endif
EOF

echo "aio-mech:${mechs}" >> "${sysdeps}"

rm -f trykqueue tryepoll trypoll tryselect1
