#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="flags-corelib"
echo "SYSDEPS aio-mech run create ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

./aio-mech ${f1_tmp}
cp ${f1_tmp} ${f1_out}
