#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

exec 1> "$1"

header="SDL_ttf.h"
path="${SYSDEP_STDINC} /usr/include/SDL /usr/local/include/SDL"
define="-DHAVE_SDL_TTF"

case "$SYSDEP_SYSTYPE" in
  darwin)
    path="/Library/Frameworks/SDL_ttf.framework/Headers \
          /sw/include/SDL ${path}"
    ;;
  sunos)
    path="/opt/csw/include/SDL ${path}"
    ;;
  *)
    ;;
esac

FLAGS="`try_manual_search "${header}" "${path}" "-I"`"
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  error "try_manual_search failed"
fi

exit 0
