#!/bin/sh

exec 1> "$1"
define="-DHAVE_NETLIB"

FLAGS=`${SYSDEP_TRY_CONFIG_BIN} "netlib-conf" "compile incdir cflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  ${SYSDEP_ERROR} "config binary failed"
fi

exit 0
