#!/bin/sh

exec 1> "$1"

args="-lglut"
path="${SYSDEP_STDLIB} /usr/X11R6/lib"
lib="libglut.so"

# What a hack.
case ${SYSDEP_OS} in
  SYSDEP_OS_DARWIN)
    lib="libglut.dylib"
    args="-framework GLUT"
    path="/System/Library/Frameworks/GLUT.framework ${path}"
    if [ -d "/System/Library/Frameworks/GLUT.framework" ]
    then
      echo ${args}
      exit 0
    fi
    ;;
  *)
    ;;
esac

FLAGS=`${SYSDEP_TRY_MANUAL} "${lib}" "${path}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  case ${SYSDEP_OS} in
    SYSDEP_OS_DARWIN)
      echo ${args}
      exit 0
      ;;
    *)
      echo ${FLAGS} ${args}
      exit 0
      ;;
    esac
else
  SYSDEP_ERROR "manual search failed"
fi

exit 0
