#!/bin/sh

fout="$1"
sdout="$2"

cleanup()
{
  rm -f trylonglong trylonglong.o
  exit 0
}

cat >> "${fout}" <<EOF
#ifndef _SD_LONGLONG_H
#define _SD_LONGLONG_H
EOF

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trylonglong.o trylonglong.c 1>/dev/null 2>&1
${SYSDEP_LD} -o trylonglong trylonglong.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#define HAVE_LONGLONG' >> "${fout}"
  echo 'longlong: yes' >> "${sdout}"
else
  echo 'longlong: no' >> "${sdout}"
fi

echo '#endif' >> "${fout}"
cleanup
