#!/bin/sh

do_clean()
{
  rm -f int32_make
}

fatal()
{
  echo "fatal: $1" 1>&2
  do_clean
  exit 1
}

tempint="$1"
tempsys="$2"

${SYSDEP_CC} -o int32_make int32_make.c
if [ $? -ne 0 ]; then fatal "error compiling int32_make"; fi
./int32_make 1>${tempint} 2>>${tempsys}
if [ $? -ne 0 ]; then fatal "could not get 32-bit signed ints"; fi

do_clean
exit 0
