#!/bin/sh

#
# This file is somewhat confusing as it is used to compile the vector
# library and also to compile programs with it.
#

f_out="$1"
f_c_out="$2"

COMP_FLAGS=""

${SYSDEP_UTIL_ECHO} ${SYSDEP_CPU_EXT} | ${SYSDEP_UTIL_GREP} 'SYSDEP_CPU_EXT_SSE' 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  COMP_FLAGS="${COMP_FLAGS} -DHAVE_CPU_EXT_SSE"
  case ${SYSDEP_CCTYPE} in
    SYSDEP_CCTYPE_GCC) COMP_FLAGS="${COMP_FLAGS} -msse";;
    SYSDEP_CCTYPE_INTEL) COMP_FLAGS="${COMP_FLAGS} -msse";;
    *) ;;
  esac
fi

${SYSDEP_UTIL_ECHO} ${SYSDEP_CPU_EXT} | ${SYSDEP_UTIL_GREP} 'SYSDEP_CPU_EXT_SSE2' 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  COMP_FLAGS="${COMP_FLAGS} -DHAVE_CPU_EXT_SSE2"
  case ${SYSDEP_CCTYPE} in
    SYSDEP_CCTYPE_GCC) COMP_FLAGS="${COMP_FLAGS} -msse2";;
    SYSDEP_CCTYPE_INTEL) COMP_FLAGS="${COMP_FLAGS} -msse2";;
    *) ;;
  esac
fi

${SYSDEP_UTIL_ECHO} ${SYSDEP_CPU_EXT} | ${SYSDEP_UTIL_GREP} 'SYSDEP_CPU_EXT_SSE3' 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  COMP_FLAGS="${COMP_FLAGS} -DHAVE_CPU_EXT_SSE3"
  case ${SYSDEP_CCTYPE} in
    SYSDEP_CCTYPE_GCC) COMP_FLAGS="${COMP_FLAGS} -msse3";;
    SYSDEP_CCTYPE_INTEL) COMP_FLAGS="${COMP_FLAGS} -msse3";;
    *) ;;
  esac
fi

${SYSDEP_UTIL_ECHO} ${SYSDEP_CPU_EXT} | ${SYSDEP_UTIL_GREP} 'SYSDEP_CPU_EXT_ALTIVEC' 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  COMP_FLAGS="${COMP_FLAGS} -DHAVE_CPU_EXT_ALTIVEC"
  case ${SYSDEP_CCTYPE} in
    SYSDEP_CCTYPE_GCC) COMP_FLAGS="${COMP_FLAGS} -faltivec";;
    *) ;;
  esac
fi

VEC_FLAGS=`eval vector-conf cflags incdir compile 2>/dev/null`
if [ $? -eq 0 ]
then
  DEFINE_LINE=`${SYSDEP_LINE} 1 < defines | ${SYSDEP_UTIL_AWK} -F: '{print $1}'`
  ${SYSDEP_UTIL_ECHO} "${VEC_FLAGS} -D${DEFINE_LINE}" >> "${f_out}"
else
  ${SYSDEP_UTIL_TOUCH} "${f_out}"
fi

${SYSDEP_UTIL_ECHO} ${COMP_FLAGS} ${VEC_FLAGS} >> "${f_c_out}"
