#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

head_out="$1"
sysd_out="$2"
sup=""

${SYSDEP_UTIL_CAT} >> "${head_out}" <<EOF
#ifndef _SD_STREAMS_H
#define _SD_STREAMS_H

EOF

sup="none"

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trystropts.o trystropts.c 2>/dev/null
${SYSDEP_LD} -o trystropts trystropts.o ${SYSDEP_LDFLAGS} 2>/dev/null
if [ $? -eq 0 ]
then
  ${SYSDEP_UTIL_ECHO} '#include <stropts.h>' >> "${head_out}"
  ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_STREAMS 1' >> "${head_out}"
  sup="streams"
fi

${SYSDEP_UTIL_CAT} >> "${head_out}" <<EOF

#endif
EOF

${SYSDEP_UTIL_ECHO} "sd-streams: ${sup}" >> "${sysd_out}"

${SYSDEP_UTIL_RM} -f trystropts trystropts.o
