#!/bin/sh

head_out="$1"
sysd_out="$2"
sup=""

cat >> "${head_out}" <<EOF
#ifndef _SD_STREAMS_H
#define _SD_STREAMS_H

EOF

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trystropts.o trystropts.c 2>/dev/null
${SYSDEP_LD} -o trystropts trystropts.o ${SYSDEP_LDFLAGS} 2>/dev/null
if [ $? -eq 0 ]
then
  echo '#include <stropts.h>' >> "${head_out}"
  echo '#define HAVE_STREAMS' >> "${head_out}"
  sup="streams"
fi

cat >> "${head_out}" <<EOF

#endif
EOF

echo "streams: ${sup}" >> "${sysd_out}"

rm -f trystropts trystropts.o
