#!/bin/sh

exec 1> "$1"

header="tiff.h"
define="-DHAVE_LIBTIFF"
path="${SYSDEP_STDINC}"

FLAGS=`${SYSDEP_TRY_MANUAL} "${header}" "${path}" "-I" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  ${SYSDEP_ERROR} "manual search failed"
fi

exit 0
