#!/bin/sh

sd_tmp="sysdeps.out"
f1_tmp="sig_action.h"
f2_tmp="sig_pmask.h"
echo "SYSDEPS signal clean ${f1_tmp} ${f2_tmp}"

outdir="`head -n 1 ../conf-outdir`"
if [ -z "${outdir}" ]
then
  echo "fatal: outdir not defined" 2>&1
  exit 1
fi
outdir="../${outdir}"
f1_out="${outdir}/${f1_tmp}"
f2_out="${outdir}/${f2_tmp}"

rm -f ${f1_tmp} ${f1_out} ${f2_tmp} ${f2_out} ${sd_tmp}
