#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

exec 1> "$1"

header="SDL.h"
define="-DHAVE_SDL"
path="${SYSDEP_STDINC} /usr/local/include/SDL /usr/include/SDL"
pkg="sdl"

case "${SYSDEP_SYSTYPE}" in
  sunos)
    path="${path} /usr/sfw/include/SDL"
    ;;
  darwin)
    path="${path} /Library/Frameworks/SDL.framework/Headers /sw/include/SDL"
    ;;
  *)
    ;;
esac

# stupid versioned 'sdl-config' freebsd workaround
FLAGS=`try_config_bin "sdl12-config" "--cflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
fi
# stupid versioned 'sdl-config' freebsd workaround
FLAGS=`try_config_bin "sdl11-config" "--cflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
fi
FLAGS=`try_config_bin "sdl-config" "--cflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
fi
error "try_config_bin failed"

FLAGS=`try_pkg_config "${pkg}" "--cflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  error "try_pkg_config failed"
fi

FLAGS=`try_manual_search "${header}" "${path}" "-I" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  error "try_manual_search failed"
fi

exit 0
