#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

search="NO"
header="SDL.h"
path="/usr/local/include/SDL"

sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
if [ x"$sys" != x ]
then
  case "$sys" in
  darwin)
    path="/Library/Frameworks/SDL.framework/Headers \
          /sw/include/SDL ${path}"
    args="-D_THREAD_SAFE"
    search="YES"
    ;;
  *)
    ;;
  esac
fi

if [ "${search}" = "YES" ]
then
  search_for "${header}" "${path}" "${args}"
  if [ $? -ne 0 ]
  then
    fatal "could not locate ${header}"
  fi
  exit 0
fi

# default sdl-config system
cf="`sdl-config --cflags`"
if [ $? -ne 0 ]
then
  fatal "error executing sdl-config"
fi

echo ${cf}
