#!/bin/sh

SYSDEP_CLEAN=1
. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="libs-math"
f2_tmp="flags-math"
f3_tmp="_sd_math.h"
echo "SYSDEPS sd-math clean ${f1_tmp} ${f2_tmp} ${f3_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"
f2_out="${SYSDEP_OUTDIR}/${f2_tmp}"
f3_out="${SYSDEP_OUTDIR}/${f3_tmp}"

rm -f ${f1_tmp} ${f1_out} ${f2_tmp} ${f2_out} ${f3_tmp} ${f3_out}
