#!/bin/sh

libs_out="$1"
flag_out="$2"

M_FLAGS=""
M_LIBS=""

cleanup()
{
  rm -f trymath1
  exit 0
}

try_math()
{
  ${SYSDEP_CC} ${M_FLAGS} -o trymath1 trymath1.c ${M_LIBS} 1>/dev/null 2>&1
  if [ $? -eq 0 ]
  then
    echo "${M_FLAGS}" >> "${flag_out}"
    echo "${M_LIBS}" >> "${libs_out}"
    return 0
  fi
  return 1
}

M_FLAGS=""
M_LIBS=""
try_math
if [ $? -eq 0 ]; then cleanup; fi

M_FLAGS=""
M_LIBS="-lm"
try_math
if [ $? -eq 0 ]; then cleanup; fi

cleanup
