#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

cleanup()
{
  ${SYSDEP_UTIL_RM} -f  \
    try_int_c99 try_int_c99.o \
    try_int_c89 try_int_c89.o \
    try_stdint try_stdint.o
}

fatal()
{
  cleanup
  SYSDEP_FATAL "$1"
  ${SYSDEP_UTIL_EXIT} 1
}

have_it()
{
  type="$1"
  extra="$2"

  ${SYSDEP_UTIL_CAT} >> "${temp_f}" <<EOF
#ifndef _SD_UINT64_H
#define _SD_UINT64_H

$extra

#define SD_UINT64_SUPPORTED 1
typedef $type sd_uint64;

#endif
EOF
  echo "sd-uint64: ${type}" >> "${temp_sys}"
  cleanup
  ${SYSDEP_UTIL_EXIT} 0
}

temp_f="$1"
temp_sys="$2"

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o try_stdint.o try_stdint.c 1>/dev/null 2>&1
${SYSDEP_LD} -o try_stdint try_stdint.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  have_it "uint64_t" "#include <stdint.h>"
fi

#
# Try C99 version.
#

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o try_int_c99.o try_int_c99.c 1>/dev/null 2>&1
${SYSDEP_LD} -o try_int_c99 try_int_c99.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  type=`./try_int_c99`
  if [ $? -eq 0 ]
  then
    have_it "${type}"
  fi
fi

#
# Test C89 version.
#

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o try_int_c89.o try_int_c89.c 1>/dev/null 2>&1
${SYSDEP_LD} -o try_int_c89 try_int_c89.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  type=`./try_int_c89`
  if [ $? -eq 0 ]
  then
    have_it "${type}"
  fi
fi

#
# Try config.
#

conf=`${SYSDEP_LINE} 1 < config`
SYSDEP_INFO "falling back to ${conf}"
type=`${SYSDEP_FILE} get "${conf}" ""`
if [ -z "${type}" ]
then
  fatal "could not get unsigned 64 bit integer type"
fi

cleanup
${SYSDEP_UTIL_EXIT} 0
