#!/bin/sh

hout="$1"
lfout="$2"
sysdeps="$3"
isoc99=0
linkflag="-lm"

lrint=0
llrint=0
lrintf=0
llrintf=0

finish()
{
  rm -f trylrint trylrintf tryllrint tryllrintf
  echo "${linkflag}" >> "${lfout}"
}

putc99()
{
  if [ ${isoc99} -eq 0 ]
  then
    cat >> "${hout}" <<EOF
#define _ISOC9X_SOURCE  1
#define _ISOC99_SOURCE  1
#define __USE_ISOC9X  1
#define __USE_ISOC99  1
#include  <math.h>
EOF
    isoc99=1
  fi
}

cat >> "${hout}" <<EOF
#ifndef _FLOATCAST_H
#define _FLOATCAST_H
EOF

cc -o trylrint trylrint.c "${linkflag}" >/dev/null 2>&1
if [ $? -eq 0 ]
then
  putc99
  echo '#define HAVE_LRINT' >> "${hout}"
  echo '#define doublecast lrint' >> "${hout}"
  lrint=1
fi

cc -o trylrintf trylrintf.c "${linkflag}" >/dev/null 2>&1
if [ $? -eq 0 ]
then
  putc99
  echo '#define HAVE_LRINTF' >> "${hout}"
  echo '#define floatcast lrintf' >> "${hout}"
  lrintf=1
fi

cc -o tryllrint tryllrint.c "${linkflag}" >/dev/null 2>&1
if [ $? -eq 0 ]
then
  putc99
  echo '#define HAVE_LLRINT' >> "${hout}"
  echo '#define lldoublecast llrint' >> "${hout}"
  llrint=1
fi

cc -o tryllrintf tryllrintf.c "${linkflag}" >/dev/null 2>&1
if [ $? -eq 0 ]
then
  putc99
  echo '#define HAVE_LLRINTF' >> "${hout}"
  echo '#define llfloatcast llrintf' >> "${hout}"
  llrintf=1
fi

echo '#endif' >> "${hout}"

if [ ${lrint} -eq 1 ]
then
  echo 'doublecast: lrint' >> "${sysdeps}"
else
  echo 'doublecast: cast' >> "${sysdeps}"
fi

if [ ${lrintf} -eq 1 ]
then
  echo 'floatcast: lrintf' >> "${sysdeps}"
else
  echo 'floatcast: cast' >> "${sysdeps}"
fi

if [ ${llrint} -eq 1 ]
then
  echo 'lldoublecast: llrint' >> "${sysdeps}"
else
  echo 'lldoublecast: cast' >> "${sysdeps}"
fi

if [ ${llrintf} -eq 1 ]
then
  echo 'llfloatcast: llrintf' >> "${sysdeps}"
else
  echo 'llfloatcast: cast' >> "${sysdeps}"
fi

finish
exit 0
