#!/bin/sh

hout="$1"
lfout="$2"
sysdeps="$3"

finish()
{
  rm -f trylrint tryllrint
  echo "-lm" >> "${lfout}"
}

cc -o trylrint trylrint.c -lm >/dev/null 2>&1
if [ $? -eq 0 ]
then
  cat >> "${hout}" <<EOF
#ifndef _FLOATCAST_H
#define _FLOATCAST_H

#define _ISOC9X_SOURCE  1
#define _ISOC99_SOURCE  1
#define __USE_ISOC9X  1
#define __USE_ISOC99  1
#include  <math.h>

#define HAVE_LRINTF
#define HAVE_LRINT
#define floatcast lrintf
#define doublecast lrint
EOF
  cc -o tryllrint tryllrint.c -lm >/dev/null 2>&1
  if [ $? -eq 0 ]
  then
    cat >> "${hout}" <<EOF
#define HAVE_LLRINTF
#define HAVE_LLRINT
#define llfloatcast llrintf
#define lldoublecast llrint

#endif
EOF
    echo "floatcast:lrint+llrint" >> "${sysdeps}"
    finish
    exit 0
  else
 cat >> "${hout}" <<EOF
#define llfloatcast(f) ((long long)(f))
#define lldoublecast(d) ((long long)(d))

#endif
EOF
    echo "floatcast:lrint+cast" >> "${sysdeps}"
    finish
    exit 0
  fi
else
  cat >> "${hout}" <<EOF
#ifndef _FLOATCAST_H
#define _FLOATCAST_H

#define floatcast(f) ((long)(f))
#define doublecast(d) ((long)(d))
#define llfloatcast(f) ((long long)(f))
#define lldoublecast(d) ((long long)(d))

#endif
EOF
  echo "floatcast:cast" >> "${sysdeps}"
  finish
  exit 0
fi
