#!/bin/sh

sd_tmp="sysdeps.out"
f1_tmp="_floatcast.h"
f2_tmp="libs-floatcast"
echo "SYSDEPS floatcast run create ${f1_tmp} ${f2_tmp}"

outdir="`head -n 1 ../conf-outdir`"
if [ -z "${outdir}" ]
then
  echo "fatal: outdir not defined" 2>&1
  exit 1
fi
outdir="../${outdir}"
f1_out="${outdir}/${f1_tmp}"
f2_out="${outdir}/${f2_tmp}"
sd_out="${outdir}/${sd_tmp}"

./floatcast ${f1_tmp} ${f2_tmp} ${sd_tmp}
cp ${f1_tmp} ${f1_out}
cp ${f2_tmp} ${f2_out}
cat ${sd_tmp} >> ${sd_out}
