#!/bin/sh

sd_tmp="sysdeps.out"
f1_tmp="_ch_flags.h"
echo "SYSDEPS ch_flags run create ${f1_tmp}"

outdir="`head -n 1 ../conf-outdir`"
if [ -z "${outdir}" ]
then
  echo "fatal: outdir not defined" 2>&1
  exit 1
fi
outdir="../${outdir}"
f1_out="${outdir}/${f1_tmp}"
sd_out="${outdir}/${sd_tmp}"

./ch_flags ${f1_tmp} ${sd_tmp}
cp ${f1_tmp} ${f1_out}
cat ${sd_tmp} >> ${sd_out}
