#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

cleanup()
{
  rm -f float32_make float32_make.o
}

fatal()
{
  cleanup
  SYSDEP_FATAL "$1"
}

have_it()
{
  type="$1"
  ${SYSDEP_UTIL_CAT} >> ${temp32} << EOF
#ifndef _SD_FLOAT32_H
#define _SD_FLOAT32_H

#define SD_FLOAT32_SUPPORTED 1

typedef ${type} sd_float32;

#endif
EOF
  ${SYSDEP_UTIL_ECHO} "sd-float32: ${type}" >> "${tempsys}"
  cleanup
  ${SYSDEP_UTIL_EXIT} 0
}

unsupported()
{
  ${SYSDEP_UTIL_CAT} >> ${temp32} << EOF
#ifndef _SD_FLOAT32_H
#define _SD_FLOAT32_H

#endif
EOF
  ${SYSDEP_UTIL_ECHO} "sd-float32: none" >> "${tempsys}"
  cleanup
  ${SYSDEP_UTIL_EXIT} 0
}

temp32="$1"
tempsys="$2"

if [ ${SYSDEP_CROSS_COMPILE} -eq 0 ]
then
  ${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o float32_make.o float32_make.c
  ${SYSDEP_LD} -o float32_make float32_make.o ${SYSDEP_LDFLAGS}
  if [ $? -ne 0 ]
  then
    unsupported
    fatal "error compiling float32_make"
  fi
  type=`./float32_make`
  if [ $? -eq 0 ];
  then
    have_it "${type}"
  fi
fi

if [ -z "${type}" ]
then
  conf=`${SYSDEP_LINE} 1 < config`
  type=`${SYSDEP_FILE} get "${conf}" ""`
  if [ -z "${type}" ]
  then
    if [ ${SYSDEP_CROSS_COMPILE} -eq 1 ]
    then
      unsupported
      fatal "cross compiling and unable to read ${conf}"
    else
      unsupported
      fatal "unable to find appropriate float32 type and unable to read ${conf}"
    fi
  else
    have_it "${type}"
  fi
fi

cleanup
${SYSDEP_UTIL_EXIT} 0
