#!/bin/sh

fout="$1"
sysdeps="$2"

cleanup()
{
  rm -f tryselect1 tryselect2 tryselect3 tryselect4 *.exe
}

cat >> "${fout}" << EOF
#ifndef _SD_SELECT_H
#define _SD_SELECT_H
EOF

${SYSDEP_CC} -o tryselect1 tryselect1.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#include <sys/select.h>' >> "${fout}"
  echo '#endif' >> "${fout}"
  echo 'select: select.h' >> "${sysdeps}"
  cleanup
  exit 0
fi

${SYSDEP_CC} -o tryselect2 tryselect2.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#include <sys/time.h>' >> "${fout}"
  echo '#endif' >> "${fout}"
  echo 'select: time.h' >> "${sysdeps}"
  cleanup
  exit 0
fi

${SYSDEP_CC} -o tryselect3 tryselect3.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#include <sys/time.h>' >> "${fout}"
  echo '#include <sys/types.h>' >> "${fout}"
  echo '#include <sys/unistd.h>' >> "${fout}"
  echo '#endif' >> "${fout}"
  echo 'select: time.h types.h unistd.h' >> "${sysdeps}"
  cleanup
  exit 0
fi

${SYSDEP_CC} -o tryselect4 tryselect4.c -lws2_32 >/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#include <winsock.h>' >> "${fout}"
  echo '#include <winbase.h>' >> "${fout}"
  echo '#endif' >> "${fout}"
  echo 'select: winsock.h winbase.h' >> "${sysdeps}"
  cleanup
  exit 0
fi

${SYSDEP_CC} -o tryselect5 tryselect5.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#include <net/socket.h>' >> "${fout}"
  echo '#endif' >> "${fout}"
  echo 'select: socket.h' >> "${sysdeps}"
  cleanup
  exit 0
fi

if [ ! -f "${sysdeps}" ]
then
  echo 'select: ' >> "${sysdeps}"
fi

echo '#endif' >> "${fout}"
