#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="`head -n 1 CREATES`"
echo "SYSDEPS altivec-flags run create ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

./altivec-flags ${f1_tmp} 
cp ${f1_tmp} ${f1_out}
