#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

do_clean()
{
  rm -f int64_make
}

fatal()
{
  echo "fatal: $1" 1>&2
  do_clean
  exit 1
}

tempint="$1"
tempsys="$2"

${SYSDEP_CC} -o int64_make int64_make.c
if [ $? -ne 0 ]; then fatal "error compiling int64_make"; fi
./int64_make 1>${tempint} 2>>${tempsys}
if [ $? -ne 0 ]; then fatal "could not get 64-bit signed ints"; fi

do_clean
exit 0
