#!/bin/sh

exec 1> "$1"

header="Fl.h"
define="-DHAVE_FLTK -DHAVE_FLTK2"
path="${SYSDEP_STDINC} /usr/X11R6/include/FL"
pkg="fltk2"

case "${SYSDEP_OS}" in
  SYSDEP_OS_DARWIN)
    path="${path} /sw/include/FL"
    ;;
  *)
    ;;
esac

FLAGS=`${SYSDEP_TRY_CONFIG_BIN} "fltk-config" "--cxxflags --use-images"
2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
fi
${SYSDEP_ERROR} "config binary failed"

FLAGS=`${SYSDEP_TRY_PKG_CONFIG} "${pkg}" "--cxxflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  ${SYSDEP_ERROR} "pkg-config failed"
fi

FLAGS=`${SYSDEP_TRY_MANUAL} "${header}" "${path}" "-I" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  ${SYSDEP_ERROR} "manual search failed"
fi

exit 0
