#!/bin/sh

f1_tmp="libs-io_poll"
echo "SYSDEPS io_poll-libs-S run create ${f1_tmp}"

outdir="`head -n 1 ../conf-outdir`"
if [ -z "${outdir}" ]
then
  echo "fatal: outdir not defined" 2>&1
  exit 1
fi
outdir="../${outdir}"
f1_out="${outdir}/${f1_tmp}"

./io_poll-libs ${f1_tmp}
cp ${f1_tmp} ${f1_out}
