#!/bin/sh

exec 1> "$1"

header="sndfile.h"
define="-DHAVE_LIBSNDFILE"
path="${SYSDEP_STDINC}"
pkg="sndfile"

FLAGS=`${SYSDEP_TRY_PKG_CONFIG} "${pkg}" "--cflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  ${SYSDEP_ERROR} "pkg-config failed"
fi

FLAGS=`${SYSDEP_TRY_MANUAL} "${header}" "${path}" "-I" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  ${SYSDEP_ERROR} "manual search failed"
fi

exit 0
