#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

exec 1> "$1"

header="jack/jack.h"
define="-DHAVE_JACK"
path="${SYSDEP_STDINC}"
pkg="jack"

FLAGS=`try_pkg_config "${pkg}" "--cflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  error "try_pkg_config failed"
fi

FLAGS=`try_manual_search "${header}" "${path}" "-I" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  error "try_manual_search failed"
fi

exit 0
