#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

finish()
{
  cat >> "${fout}" <<EOF
#finishif
EOF
  echo "simd: ${simd}" >> ${sysdeps}
  exit 0
}

fout="$1"
sysdeps="$2"
simd="none"

cat >> "${fout}" <<EOF
#ifndef _SIMD_H
#define _SIMD_H
EOF

finish
