#!/bin/sh

fout="$1"
sysdeps="$2"
sup=""

cat >> "${fout}" <<EOF
#ifndef _SD_FCNTL_H
#define _SD_FCNTL_H

EOF

${SYSDEP_CC} -o tryfcntl tryfcntl.c 2>/dev/null
if [ $? -eq 0 ]
then
  echo '#include <fcntl.h>' >> "${fout}"
  echo '#define HAVE_FCNTL' >> "${fout}"
  sup="fcntl ${sup}"
fi

${SYSDEP_CC} -o tryioctlsock tryioctlsock.c -lws2_32 2>/dev/null
if [ $? -eq 0 ]
then
  echo '#include <winsock.h>' >> "${fout}"
  echo '#define HAVE_IOCTLSOCKET' >> "${fout}"
  sup="ioctlsocket ${sup}"
fi

cat >> "${fout}" <<EOF

#ifndef O_NONBLOCK
  #ifdef O_NDELAY
    #define O_NONBLOCK O_NDELAY
  #else
    #define O_NONBLOCK 0
  #endif
#endif

#endif
EOF

echo "fcntl: ${sup}" >> "${sysdeps}"
rm -f tryfcntl tryioctlsock
