#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

sd_tmp="sysdeps.out"
f1_tmp="_sd_fcntl.h"
f2_tmp="flags-fcntl"
f3_tmp="libs-fcntl"
echo "SYSDEPS sd-fcntl run create ${f1_tmp} ${f2_tmp} ${f3_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"
f2_out="${SYSDEP_OUTDIR}/${f2_tmp}"
f3_out="${SYSDEP_OUTDIR}/${f3_tmp}"
sd_out="${SYSDEP_OUTDIR}/${sd_tmp}"

./fcntl ${f1_tmp} ${f2_tmp} ${f3_tmp} ${sd_tmp}
cp ${f1_tmp} ${f1_out}
cp ${f2_tmp} ${f2_out}
cp ${f3_tmp} ${f3_out}
cat ${sd_tmp} >> ${sd_out}
