#!/bin/sh

do_clean()
{
  rm -f make-byteorder make-byteorder.o
}

fatal()
{
  echo "fatal: $1" 1>&2
  do_clean
  exit 1
}

temph="$1"
tempsys="$2"

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o make-byteorder.o make-byteorder.c
${SYSDEP_LD} -o make-byteorder make-byteorder.o ${SYSDEP_LDFLAGS}
if [ $? -ne 0 ]; then fatal "error compiling make-byteorder"; fi

./make-byteorder 1>${temph} 2>>${tempsys}
if [ $? -ne 0 ]; then fatal "could not create make-byteorder header"; fi

do_clean
exit 0
