#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="flags-sdl-image"
echo "SYSDEPS sdl-image-flags run create ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

./sdl-image-flags ${f1_tmp}
cp ${f1_tmp} ${f1_out}
