#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

search="NO"
header="SDL_image.h"
path="/usr/include/SDL /usr/local/include/SDL"
define="-DSYSD_HAVE_SDL_IMAGE"

sys="`uname -s | tr '/:[A-Z]' '..[a-z]'`"
if [ x"$sys" != x ]
then
  case "$sys" in
  darwin)
    path="/Library/Frameworks/SDL_image.framework/Headers \
          /sw/include/SDL ${path}"
    search="YES"
    ;;
  sunos)
    path="/opt/csw/include/SDL ${path}"
    search="YES"
    ;;
  *)
    search="YES"
    ;;
  esac
fi

args="${define}"
if [ "${search}" = "YES" ]
then
  search_header "${header}" "${path}" "${args}"
  if [ $? -ne 0 ]
  then
    error "could not locate ${header}"
  fi
  exit 0
fi

# can't get here
