#!/bin/sh

SYSDEP_CLEAN=1
. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

sd_tmp="sysdeps.out"
f1_tmp="_sig_action.h"
f2_tmp="_sig_pmask.h"
echo "SYSDEPS sd-signal clean ${f1_tmp} ${f2_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"
f2_out="${SYSDEP_OUTDIR}/${f2_tmp}"

rm -f ${f1_tmp} ${f1_out} ${f2_tmp} ${f2_out} ${sd_tmp}
