#!/bin/sh

sigact_out="$1"
sigpm_out="$2"
sysdeps="$3"

${SYSDEP_UTIL_CAT} >> "${sigact_out}" <<EOF
#ifndef _SD_SIG_ACTION_H
#define _SD_SIG_ACTION_H
EOF

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trysigact.o trysigact.c >/dev/null 2>&1
${SYSDEP_LD} -o trysigact trysigact.o ${SYSDEP_LDFLAGS} >/dev/null 2>&1
if [ $? -eq 0 ]
then
  ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_SIGACTION 1' >> "${sigact_out}"
  ${SYSDEP_UTIL_ECHO} 'sd-sigaction: sigaction' >> "${sysdeps}"
else
  ${SYSDEP_UTIL_ECHO} 'sd-sigaction: none' >> "${sysdeps}"
fi

${SYSDEP_UTIL_ECHO} '#endif' >> "${sigact_out}"

${SYSDEP_UTIL_CAT} >> "${sigpm_out}" <<EOF
#ifndef _SD_SIG_PMASK_H
#define _SD_SIG_PMASK_H
EOF

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trysigpm.o trysigpm.c >/dev/null 2>&1
${SYSDEP_LD} -o trysigpm trysigpm.o ${SYSDEP_LDFLAGS} >/dev/null 2>&1
if [ $? -eq 0 ]
then
  ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_SIGPROCMASK 1' >> "${sigpm_out}"
  ${SYSDEP_UTIL_ECHO} 'sd-sigprocmask: sigprocmask' >> "${sysdeps}"
else
  ${SYSDEP_UTIL_ECHO} 'sd-sigprocmask: none' >> "${sysdeps}"
fi

${SYSDEP_UTIL_ECHO} '#endif' >> "${sigpm_out}"

${SYSDEP_UTIL_RM} -f trysigpm trysigact trysigpm.o trysigact.o
