#!/bin/sh

fatal()
{
  echo "fatal: $1" 1>&2
  exit 1
}

temph="$1"
tempsys="$2"

cc -o endian endian.c
if [ $? -ne 0 ]; then fatal "error compiling endian"; fi

./endian 1>${temph} 2>>${tempsys}
if [ $? -ne 0 ]; then fatal "could not create endian header"; fi

exit 0
