#!/bin/sh

fout="$1"
sysdeps="$2"

${SYSDEP_CC} ${SYSDEP_CFLAGS} -o trydirent.o -c trydirent.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  cat > "${fout}" <<EOF
#ifndef _DIRENTRY_H
#define _DIRENTRY_H

#include <sys/types.h>
#include <dirent.h>
#define direntry struct dirent

#endif
EOF
  echo "direntry: struct dirent" >> "${sysdeps}"
else
  cat > "${fout}" <<EOF
#ifndef _DIRENTRY_H
#define _DIRENTRY_H

#include <sys/types.h>
#include <sys/dir.h>
#define direntry struct direct

#endif
EOF
  echo "direntry: struct direct" >> "${sysdeps}"
fi

rm -f trydirent.o
