#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="flags-fltk2"
echo "SYSDEPS fltk2-flags run create ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

./fltk2-flags ${f1_tmp}
cp ${f1_tmp} ${f1_out}
