#!/bin/sh

exec 1> "$1"

header="SDL_ttf.h"
path="${SYSDEP_STDINC} /usr/include/SDL /usr/local/include/SDL"
define="-DHAVE_SDL_TTF"

case "$SYSDEP_SYSTYPE" in
  SYSDEP_OS_DARWIN)
    path="/Library/Frameworks/SDL_ttf.framework/Headers \
          /sw/include/SDL ${path}"
    ;;
  SYSDEP_OS_SUNOS)
    path="/opt/csw/include/SDL ${path}"
    ;;
  *)
    ;;
esac

FLAGS="`${SYSDEP_TRY_MANUAL} "${header}" "${path}" "-I"`"
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  ${SYSDEP_ERROR} "manual search failed"
fi

exit 0
