#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

do_clean()
{
  rm -f float64_make float64_make
}

fatal()
{
  echo "fatal: $1" 1>&2
  do_clean
  exit 1
}

temp64="$1"
tempsys="$2"

${SYSDEP_CC} -o float64_make float64_make.c
if [ $? -ne 0 ]; then fatal "error compiling float64_make"; fi
./float64_make 1>${temp64} 2>>${tempsys}
if [ $? -ne 0 ]; then fatal "could not get 64-bit floats"; fi

do_clean
exit 0
