#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

fout="$1"
sysdeps="$2"

cleanup_exit()
{
  ${SYSDEP_UTIL_RM} -f trymmap1 trymmap1.o
  ${SYSDEP_UTIL_EXIT} 0
}

have_mmap()
{
  ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_MMAP' >> "${fout}"
  ${SYSDEP_UTIL_ECHO} 'sd-mmap: mmap' >> "${sysdeps}"

  ${SYSDEP_UTIL_CAT} >> "${fout}" <<EOF
#include <sys/types.h>
#include <sys/mman.h>
EOF
}

no_mmap()
{
  ${SYSDEP_UTIL_ECHO} 'sd-mmap: none' >> "${sysdeps}"
}

try_mmap()
{
  ${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trymmap1.o trymmap1.c  1>/dev/null 2>&1
  ${SYSDEP_LD} -o trymmap1 trymmap1.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
  if [ $? -eq 0 ]
  then
    return 1
  else
    return 0
  fi
}

try_run_mmap()
{
  ./trymmap1
  if [ $? -eq 0 ]
  then
    return 1
  else
    return 0
  fi
}

header_open()
{
  ${SYSDEP_UTIL_CAT} >> "${fout}" <<EOF
#ifndef _SD_MMAP_H
#define _SD_MMAP_H

EOF
}

header_close()
{
  ${SYSDEP_UTIL_CAT} >> "${fout}" <<EOF

#endif
EOF
}

success()
{
  header_open
  have_mmap
  header_close
  cleanup_exit
}

fail()
{
  header_open
  no_mmap
  header_close
  cleanup_exit
}

CONFIG_FILE="`${SYSDEP_LINE} 1 < config`" ||
  SYSDEP_FATAL "could not determine config"

if [ ${SYSDEP_CROSS_COMPILE} -eq 1 ]
then
  ${SYSDEP_FILE} exists "${CONFIG_FILE}"
  if [ $? -eq 0 ]
  then
    CONFIG_VALUE=`${SYSDEP_LINE} 1 < "${CONFIG_FILE}"` ||
      SYSDEP_FATAL "could not read configuration file"
    case ${CONFIG_VALUE} in
      mmap) success ;;
      none) fail    ;;
      *)    SYSDEP_FATAL "invalid value specified in config file (mmap|none)"
    esac
  else
    SYSDEP_FATAL "cross compiling requires configuration file (${CONFIG_FILE})"
  fi
else
  try_mmap     || fail
  try_run_mmap || fail
  success
fi
