#!/bin/sh

fout="$1"
sysdeps="$2"

cat >> "${fout}" <<EOF
#ifndef _SD_MMAP_H
#define _SD_MMAP_H

EOF

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trymmap1.o trymmap1.c  1>/dev/null 2>&1
${SYSDEP_LD} -o trymmap1 trymmap1.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  ./trymmap1
  if [ $? -eq 0 ]
  then
    echo '#define HAVE_MMAP' >> "${fout}"
    echo 'mmap: mmap' >> "${sysdeps}"
  else
    echo 'mmap: none' >> "${sysdeps}"
  fi
else
  echo 'mmap: none' >> "${sysdeps}"
fi

cat >> "${fout}" <<EOF

#include <sys/types.h>
#include <sys/mman.h>
#endif
EOF

rm -f trymmap1
