#!/bin/sh

fout="$1"
sysdeps="$2"

cat >> "${fout}" <<EOF
#ifndef _SD_MMAP_H
#define _SD_MMAP_H

EOF

sd_done=0
${SYSDEP_CC} -o trymmap trymmap.c  1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  ./trymmap
  if [ $? -eq 0 ]
  then
    echo '#define HAVE_MMAP' >> "${fout}"
    echo 'mmap: mmap' >> "${sysdeps}"
  else
    echo 'mmap: ' >> "${sysdeps}"
  fi
else
  echo 'mmap: ' >> "${sysdeps}"
fi
cat >> "${fout}" <<EOF

#include <sys/types.h>
#include <sys/mman.h>
#endif
EOF

rm -f trymmap
