#!/bin/sh

fout="$1"
sysdeps="$2"

cat >> "${fout}" <<EOF
#ifndef _IOMECH_H
#define _IOMECH_H
EOF

cc -o trykqueue trykqueue.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#define HAVE_KQUEUE 1' >> "${fout}" 
  mechs="${mechs} kqueue"
fi

cc -o trypoll trypoll.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#define HAVE_POLL 1' >> "${fout}"
  mechs="${mechs} poll"
fi

cc -o tryselect tryselect.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  echo '#define HAVE_SELECT 1' >> "${fout}"
  mechs="${mechs} select"
fi

cat >> "${fout}" <<EOF
#endif
EOF

echo "iomech:${mechs}" >> "${sysdeps}"

rm -f trykqueue trypoll tryselect
