#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="libs-sndfile"
echo "SYSDEPS sndfile-libs run create ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

./sndfile-libs ${f1_tmp}
cp ${f1_tmp} ${f1_out}
