#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

sd_tmp="sysdeps.out"
f1_tmp="_io-notice.h"
echo "SYSDEPS io-notice run create ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"
sd_out="${SYSDEP_OUTDIR}/${sd_tmp}"

./io-notice ${f1_tmp} ${sd_tmp}
cp ${f1_tmp} ${f1_out}
cat ${sd_tmp} >> ${sd_out}

