#!/bin/sh

exec 1> "$1"

path="${SYSDEP_STDLIB}"
pkg="portaudio"
lib="lib${pkg}.${SYSDEP_LIBSUFFIX}"
EXTRA_FLAGS="-lportaudio"

case "${SYSDEP_SYSTYPE}" in
  SYSDEP_OS_DARWIN)
    path="${path} /sw/lib"
    EXTRA_FLAGS="${EXTRA_FLAGS} -framework AudioToolbox -framework CoreAudio"
    ;;
  *)
    EXTRA_FLAGS="${EXTRA_FLAGS} -lpthread"
    ;; 
esac

FLAGS=`${SYSDEP_TRY_MANUAL} "${lib}" "${path}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${EXTRA_FLAGS}
  exit 0
else
  ${SYSDEP_ERROR} "manual search failed"
fi

exit 0
