#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

fout="$1"
lout="$2"
sysdeps="$3"

finish()
{
${SYSDEP_UTIL_CAT} >> "${fout}" <<EOF
#endif
EOF
  ${SYSDEP_UTIL_RM} -f \
    trybsd1 trybsd1.o \
    trysysv1 trysysv1.o \
    tryhpux1 tryhpux1.o

  ${SYSDEP_UTIL_TOUCH} "${lout}"
  ${SYSDEP_UTIL_EXIT} 0
}

${SYSDEP_UTIL_CAT} >> "${fout}" <<EOF
#ifndef _SD_SENDFILE_H
#define _SD_SENDFILE_H
EOF

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trybsd1.o trybsd1.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  ${SYSDEP_LD} -o trybsd1 trybsd1.o ${SYSDEP_LDFLAGS} >/dev/null 2>&1
  if [ $? -eq 0 ]
  then
    ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_SENDFILE 1' >> "${fout}"
    ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_SENDFILE_BSD 1' >> "${fout}"
    ${SYSDEP_UTIL_ECHO} "sd-sendfile: bsd" >> "${sysdeps}"
    ${SYSDEP_UTIL_ECHO} "sd-sendfile-libs: " >> "${sysdeps}"
    finish
  fi
fi

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trysysv1.o trysysv1.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  ${SYSDEP_LD} -o trysysv1 trysysv1.o ${SYSDEP_LDFLAGS} >/dev/null 2>&1
  if [ $? -eq 0 ]
  then
    ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_SENDFILE 1' >> "${fout}"
    ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_SENDFILE_SYSV 1' >> "${fout}"
    ${SYSDEP_UTIL_ECHO} "sd-sendfile: sysv" >> "${sysdeps}"
    ${SYSDEP_UTIL_ECHO} "sd-sendfile-libs: " >> "${sysdeps}"
    finish
  else
    ${SYSDEP_LD} -o trysysv1 trysysv1.o ${SYSDEP_LDFLAGS} -lsendfile >/dev/null 2>&1
    if [ $? -eq 0 ]
    then
      ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_SENDFILE 1' >> "${fout}"
      ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_SENDFILE_SYSV 1' >> "${fout}"
      ${SYSDEP_UTIL_ECHO} "sd-sendfile: sysv" >> "${sysdeps}"
      ${SYSDEP_UTIL_ECHO} "-lsendfile" >> "${lout}"
      ${SYSDEP_UTIL_ECHO} "sd-sendfile-libs: -lsendfile" >> "${sysdeps}"
      finish
    fi
  fi
fi

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o tryhpux1.o tryhpux1.c >/dev/null 2>&1
if [ $? -eq 0 ]
then
  ${SYSDEP_LD} -o tryhpux1 tryhpux1.o ${SYSDEP_LDFLAGS} >/dev/null 2>&1
  if [ $? -eq 0 ]
  then
    ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_SENDFILE 1' >> "${fout}"
    ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_SENDFILE_HPUX 1' >> "${fout}"
    ${SYSDEP_UTIL_ECHO} "sd-sendfile: hpux" >> "${sysdeps}"
    ${SYSDEP_UTIL_ECHO} "sd-sendfile-libs: " >> "${sysdeps}"
    finish
  fi
fi

${SYSDEP_UTIL_ECHO} "sd-sendfile: none" >> "${sysdeps}"
${SYSDEP_UTIL_ECHO} "sd-sendfile-libs: " >> "${sysdeps}"
finish
