#!/bin/sh

. ../sysdep-subs
if [ $? -ne 0 ]
then
  exit 111
fi

do_clean()
{
  rm -f float32_make float64_make
}

fatal()
{
  echo "fatal: $1" 1>&2
  do_clean
  exit 1
}

temp32="$1"
tempsys="$2"

${SYSDEP_CC} -o float32_make float32_make.c
if [ $? -ne 0 ]; then fatal "error compiling float32_make"; fi
./float32_make 1>${temp32} 2>>${tempsys}
if [ $? -ne 0 ]; then fatal "could not get 32-bit floats"; fi

do_clean
exit 0
