#!/bin/sh

exec 1> "$1"

header="SDL.h"
define="-DHAVE_SDL"
path="${SYSDEP_STDINC} /usr/local/include/SDL /usr/include/SDL"
pkg="sdl"

case "${SYSDEP_OS}" in
  SYSDEP_OS_SUNOS)
    path="${path} /usr/sfw/include/SDL"
    ;;
  SYSDEP_OS_DARWIN)
    define="${define} -D_REENTRANT"
    path="${path} /Library/Frameworks/SDL.framework/Headers /sw/include/SDL"
    ;;
  *)
    ;;
esac

FLAGS=`${SYSDEP_TRY_CONFIG_BIN} "sdl-config" "--cflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
fi
${SYSDEP_ERROR} "config binary failed"

FLAGS=`${SYSDEP_TRY_PKG_CONFIG} "${pkg}" "--cflags" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  ${SYSDEP_ERROR} "pkg-config failed"
fi

FLAGS=`${SYSDEP_TRY_MANUAL} "${header}" "${path}" "-I" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo ${FLAGS} ${define}
  exit 0
else
  ${SYSDEP_ERROR} "manual search failed"
fi

exit 0
