#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="flags-io_poll"
echo "SYSDEPS io_poll-flags run create ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

./io_poll-flags ${f1_tmp}
cp ${f1_tmp} ${f1_out}
