#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

exec 1> "$1"

args="-lGL"
path="${SYSDEP_STDLIB} /usr/X11R6/lib"
lib="libGL.so"

case ${SYSDEP_OS} in
  SYSDEP_OS_DARWIN)
    lib="libGL.dylib"
    args="-framework OpenGL"
    path="/System/Library/Frameworks/OpenGL.framework ${path}"
    ;;
  *)
    ;;
esac

FLAGS=`${SYSDEP_TRY_MANUAL} "${lib}" "${path}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  case ${SYSDEP_OS} in
    SYSDEP_OS_DARWIN)
      ${SYSDEP_UTIL_ECHO} ${args}
      ${SYSDEP_UTIL_EXIT} 0
      ;;
    *)
      ${SYSDEP_UTIL_ECHO} ${FLAGS} ${args}
      ${SYSDEP_UTIL_EXIT} 0
      ;;
    esac
else
  SYSDEP_ERROR "manual search failed"
fi

${SYSDEP_UTIL_EXIT} 0
