#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

fout="$1"
sysdep="$2"

cleanup()
{
  rm -f trychflags trychflags.o
}

have_chflags()
{
  define=`${SYSDEP_LINE} 1 < defines`
  ${SYSDEP_UTIL_CAT} > "${fout}" <<EOF
#ifndef _SD_CHFLAGS_H
#define _SD_CHFLAGS_H

#define $define

#endif
EOF
  ${SYSDEP_UTIL_ECHO} "sd-chflags: chflags" >> "${sysdep}"
  cleanup
  ${SYSDEP_UTIL_EXIT} 0
}

no_chflags()
{
  ${SYSDEP_UTIL_CAT} > "${fout}" <<EOF
#ifndef _SD_CHFLAGS_H
#define _SD_CHFLAGS_H

#endif
EOF
  ${SYSDEP_UTIL_ECHO} "sd-chflags: none" >> "${sysdep}"
  cleanup
  ${SYSDEP_UTIL_EXIT} 0
}

conf=`${SYSDEP_LINE} 1 < config`

if [ ${SYSDEP_CROSS_COMPILE} -eq 1 ]
then
  have=`${SYSDEP_FILE} get "${conf}" ""`
  if [ ! -z "${have}" ]
  then
    case "${have}" in
      chflags)
        have_chflags;;
      none)
        no_chflags;;
      *)
        SYSDEP_ERROR "unexpected value in ${conf}"
        no_chflags;;
    esac
  fi
fi

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o trychflags.o trychflags.c >/dev/null 2>&1
${SYSDEP_LD} -o trychflags trychflags.o ${SYSDEP_LDFLAGS} >/dev/null 2>&1
if [ $? -eq 0 ];
then
  have_chflags;
else
  no_chflags;
fi
