#!/bin/sh

fout="$1"
sysdeps="$2"

cat >> "${fout}" <<EOF
#ifndef _DUP2_H
#define _DUP2_H

EOF

cc -o trydup2 trydup2.c
if [ $? -eq 0 ]
then
  echo '#define HAVE_DUP2' >> "${fout}"
  echo 'fd_dup2:dup2' >> "${sysdeps}"
else
  echo 'fd_dup2:none' >> "${sysdeps}"
fi

echo '#endif' >> "${fout}"
rm -f trydup2
