#!/bin/sh

do_clean()
{
  rm -f uint16_make
}

fatal()
{
  echo "fatal: $1" 1>&2
  do_clean
  exit 1
}

tempuint="$1"
tempsys="$2"

${SYSDEP_CC} -o uint16_make uint16_make.c
if [ $? -ne 0 ]; then fatal "error compiling uint16_make"; fi
./uint16_make 1>${tempuint} 2>>${tempsys}
if [ $? -ne 0 ]; then fatal "could not get 16-bit unsigned ints"; fi

do_clean
exit 0
