#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

fout="$1"
sysdeps="$2"

${SYSDEP_UTIL_CAT} >> "${fout}" <<EOF
#ifndef _SD_FORK_H
#define _SD_FORK_H

EOF

SD_HAVE_FORK=0
SD_HAVE_VFORK=0

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o tryfork.o tryfork.c  1>/dev/null 2>&1
${SYSDEP_LD} -o tryfork tryfork.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  ./tryfork
  if [ $? -eq 0 ]
  then
    SD_HAVE_FORK=1
  fi
fi

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o tryvfork.o tryvfork.c  1>/dev/null 2>&1
${SYSDEP_LD} -o tryvfork tryvfork.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  ./tryvfork
  if [ $? -eq 0 ]
  then
    SD_HAVE_VFORK=1
  fi
fi

if [ ${SD_HAVE_FORK} -eq 1 ]
then
  ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_FORK 1' >> "${fout}"
  if [ ${SD_HAVE_VFORK} -eq 1 ]
  then
    ${SYSDEP_UTIL_ECHO} '#define SD_HAVE_VFORK 1' >> "${fout}"
    ${SYSDEP_UTIL_ECHO} 'sd-fork: fork vfork' >> "${sysdeps}"
  else
    ${SYSDEP_UTIL_ECHO} 'sd-fork: fork' >> "${sysdeps}"
  fi
else
  ${SYSDEP_UTIL_ECHO} 'sd-fork: ' >> "${sysdeps}"
fi

${SYSDEP_UTIL_CAT} >> "${fout}" <<EOF

#endif
EOF

${SYSDEP_UTIL_RM} -f tryfork tryfork.o tryvfork tryvfork.o
