#!/bin/sh

fout="$1"
sysdeps="$2"

cat >> "${fout}" <<EOF
#ifndef _SD_FORK_H
#define _SD_FORK_H

EOF

HAVE_FORK=0
HAVE_VFORK=0

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o tryfork.o tryfork.c  1>/dev/null 2>&1
${SYSDEP_LD} -o tryfork tryfork.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  ./tryfork
  if [ $? -eq 0 ]
  then
    HAVE_FORK=1
  fi
fi

${SYSDEP_CC} ${SYSDEP_CFLAGS} -c -o tryvfork.o tryvfork.c  1>/dev/null 2>&1
${SYSDEP_LD} -o tryvfork tryvfork.o ${SYSDEP_LDFLAGS} 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  ./tryvfork
  if [ $? -eq 0 ]
  then
    HAVE_VFORK=1
  fi
fi

if [ $HAVE_FORK -eq 1 ]
then
  echo '#define HAVE_FORK' >> "${fout}"
  if [ $HAVE_VFORK -eq 1 ]
  then
    echo '#define HAVE_VFORK' >> "${fout}"
    echo 'fork: fork vfork' >> "${sysdeps}"
  else
    echo 'fork: fork' >> "${sysdeps}"
  fi
else
  echo 'fork: ' >> "${sysdeps}"
fi

cat >> "${fout}" <<EOF

#endif
EOF

rm -f tryfork tryfork.o tryvfork tryvfork.o
