#!/bin/sh

SYSDEP_CLEAN=1
. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

sd_tmp="sysdeps.out"
f1_tmp="_sysinfo.h"
echo "SYSDEPS sysinfo clean ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

rm -f ${f1_tmp} ${f1_out} ${sd_tmp}
