#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

fout="$1"
sysdeps="$2"

define()
{
  echo "#define $1 $2" >> "${fout}" ||
    SYSDEP_FATAL "could not write ${fout}"
}

(
cat >> "${fout}" <<EOF
#ifndef SD_SYSINFO_H
#define SD_SYSINFO_H

EOF
) || SYSDEP_FATAL "could not write ${fout}"

cat ${SYSDEP_BASE_DIRECTORY}/sd-sysinfo.h >> "${fout}" ||
  SYSDEP_FATAL "could not write ${fout}"
echo >> "${fout}" ||
  SYSDEP_FATAL "could not write ${fout}"

#----------------------------------------------------------------------
# C

define SD_SYSINFO_OS "${SYSDEP_OS}"
define SD_SYSINFO_OSVERSION \""${SYSDEP_OSVERSION}"\"
define SD_SYSINFO_ARCH "${SYSDEP_ARCH}"
define SD_SYSINFO_CCTYPE "${SYSDEP_CCTYPE}"
define SD_SYSINFO_CFLAGS \""${SYSDEP_CFLAGS}"\"
define SD_SYSINFO_LDFLAGS \""${SYSDEP_LDFLAGS}"\"
define SD_SYSINFO_CCVERSION \""${SYSDEP_CCVERSION}"\"

major=`echo "${SYSDEP_CCVERSION}" | awk -F. '{print $1}'` ||
  SYSDEP_FATAL "could not get C compiler major version"
minor=`echo "${SYSDEP_CCVERSION}" | awk -F. '{print $2}'` ||
  SYSDEP_FATAL "could not get C compiler minor version"
patch=`echo "${SYSDEP_CCVERSION}" | awk -F. '{print $3}'` ||
  SYSDEP_FATAL "could not get C compiler patch version"

define SD_SYSINFO_CCVERSION_MAJOR "$major"
define SD_SYSINFO_CCVERSION_MINOR "$minor"
define SD_SYSINFO_CCVERSION_PATCH "$patch"

#----------------------------------------------------------------------
# Ada

if [ ! -z "${SYSDEP_ADA_COMP}" ]
then
  define SD_SYSINFO_ADA_CFLAGS \""${SYSDEP_ADA_CFLAGS}"\"
  define SD_SYSINFO_ADA_BFLAGS \""${SYSDEP_ADA_BFLAGS}"\"
  define SD_SYSINFO_ADA_LDFLAGS \""${SYSDEP_ADA_LDFLAGS}"\"

  major=`echo "${SYSDEP_ADA_VERSION}" | awk -F. '{print $1}'` ||
    SYSDEP_FATAL "could not get Ada compiler major version"
  minor=`echo "${SYSDEP_ADA_VERSION}" | awk -F. '{print $2}'` ||
    SYSDEP_FATAL "could not get Ada compiler minor version"
  patch=`echo "${SYSDEP_ADA_VERSION}" | awk -F. '{print $3}'` ||
    SYSDEP_FATAL "could not get Ada compiler patch version"

  define SD_SYSINFO_ADA_TYPE "${SYSDEP_ADA_TYPE}"
  define SD_SYSINFO_ADA_VERSION \""${SYSDEP_ADA_VERSION}"\"
  define SD_SYSINFO_ADA_VERSION_MAJOR "$major"
  define SD_SYSINFO_ADA_VERSION_MINOR "$minor"
  define SD_SYSINFO_ADA_VERSION_PATCH "$patch"
fi

#----------------------------------------------------------------------
# cpu

define SD_SYSINFO_CPU_NUM "${SYSDEP_CPU_NUM}"
define SD_SYSINFO_CPU_L1_INST_CACHE_SIZE "${SYSDEP_CPU_L1_INST_CACHE_SIZE}"
define SD_SYSINFO_CPU_L1_DATA_CACHE_SIZE "${SYSDEP_CPU_L1_DATA_CACHE_SIZE}"
define SD_SYSINFO_CPU_L2_CACHE_SIZE "${SYSDEP_CPU_L2_CACHE_SIZE}"
define SD_SYSINFO_CPU_L3_CACHE_SIZE "${SYSDEP_CPU_L3_CACHE_SIZE}"
define SD_SYSINFO_CPU_CACHE_LINE_SIZE "${SYSDEP_CPU_CACHE_LINE_SIZE}"
define SD_SYSINFO_CPU_FREQ "${SYSDEP_CPU_FREQ}"

ext="(0"
for f in ${SYSDEP_CPU_EXT}
do
  ext="${ext} | $f"
done
ext="${ext})"
define SD_SYSINFO_CPU_EXT "${ext}"

for f in ${SYSDEP_CPU_EXT}
do
  have=`echo "${f}" | sed -e 's/SD_SYSINFO_/SD_SYSINFO_HAVE_/g'` ||
    SYSDEP_FATAL "could not convert \"$f\" to SYSINFO form"
  define "${have}"
done

cat >> "${fout}" <<EOF

#endif /* SD_SYSINFO_H */
EOF

os=`grep 'SD_SYSINFO_OS ' "${fout}" \
 | sed -e 's/SD_SYSINFO_OS_//g' | awk '{print $NF}'` ||
  SYSDEP_FATAL "could not extract OS"
ver=`grep 'SD_SYSINFO_OSVERSION ' "${fout}" \
 | sed -e 's/SD_SYSINFO_OSVERSION_//g' | awk '{print $NF}'` ||
  SYSDEP_FATAL "could not extract OS version"
cc=`grep 'SD_SYSINFO_CCTYPE ' "${fout}" \
 | sed -e 's/SD_SYSINFO_CCTYPE_//g' | awk '{print $NF}'` ||
  SYSDEP_FATAL "could not extract C compiler type"
ccver=`grep 'SD_SYSINFO_CCVERSION ' "${fout}" \
 | sed -e 's/SD_SYSINFO_CCVERSION//g' | awk '{print $NF}'` ||
  SYSDEP_FATAL "could not extract C compiler version"
arch=`grep 'SD_SYSINFO_ARCH ' "${fout}" \
 | sed -e 's/SD_SYSINFO_ARCH_//g' | awk '{print $NF}'` ||
  SYSDEP_FATAL "could not extract hardware architecture"
ada=`grep 'SD_SYSINFO_ADA_TYPE ' "${fout}" \
 | sed -e 's/SD_SYSINFO_ADA_TYPE_//g' | awk '{print $NF}'` ||
  SYSDEP_FATAL "could not extract Ada compiler type"
adaver=`grep 'SD_SYSINFO_ADA_VERSION ' "${fout}" \
 | sed -e 's/SD_SYSINFO_ADA_VERSION//g' | awk '{print $NF}'` ||
  SYSDEP_FATAL "could not extract Ada compiler version"

echo "sysinfo: ${os} ${ver} ${cc} ${ccver} ${arch} ${ada} ${adaver}" \
  | tr [A-Z] [a-z] | sed -e 's/"//g' >> "${sysdeps}" ||
  SYSDEP_FATAL "could not write \"${sysdeps}\""
echo "sysinfo-cflags: ${SYSDEP_CFLAGS}" >> "${sysdeps}" ||
  SYSDEP_FATAL "could not write \"${sysdeps}\""
echo "sysinfo-ldflags: ${SYSDEP_LDFLAGS}" >> "${sysdeps}" ||
  SYSDEP_FATAL "could not write \"${sysdeps}\""
echo "sysinfo-ada-cflags: ${SYSDEP_ADA_CFLAGS}" >> "${sysdeps}" ||
  SYSDEP_FATAL "could not write \"${sysdeps}\""
echo "sysinfo-ada-bflags: ${SYSDEP_ADA_BFLAGS}" >> "${sysdeps}" ||
  SYSDEP_FATAL "could not write \"${sysdeps}\""
echo "sysinfo-ada-ldflags: ${SYSDEP_ADA_LDFLAGS}" >> "${sysdeps}" ||
  SYSDEP_FATAL "could not write \"${sysdeps}\""
