#!/bin/sh

. ../../sysdep-main
if [ $? -ne 0 ]
then
  exit 111
fi

f1_tmp="_sysinfo.h"
echo "SYSDEPS sysinfo run create ${f1_tmp}"

f1_out="${SYSDEP_OUTDIR}/${f1_tmp}"

./sysinfo ${f1_tmp}
cp ${f1_tmp} ${f1_out}
