#!/bin/sh

fout="$1"
sysdeps="$2"

define()
{
  echo "#define $1 $2" | sed -e 's/SYSDEP/SYSINFO/g' >> "${fout}"
}

cat >> "${fout}" <<EOF
#ifndef _SYSINFO_H
#define _SYSINFO_H

EOF

define SYSINFO_OS ${SYSDEP_OS}
define SYSINFO_ARCH ${SYSDEP_ARCH}
define SYSINFO_CPU_NUM ${SYSDEP_CPU_NUM}
define SYSINFO_CPU_MODEL ${SYSDEP_CPU_MODEL}
define SYSINFO_CPU_L1_INST_CACHE_SIZE ${SYSDEP_CPU_L1_INST_CACHE_SIZE}
define SYSINFO_CPU_L1_DATA_CACHE_SIZE ${SYSDEP_CPU_L1_DATA_CACHE_SIZE}
define SYSINFO_CPU_L2_CACHE_SIZE ${SYSDEP_CPU_L2_CACHE_SIZE}
define SYSINFO_CPU_L3_CACHE_SIZE ${SYSDEP_CPU_L3_CACHE_SIZE}
define SYSINFO_CPU_CACHE_LINE_SIZE ${SYSDEP_CPU_CACHE_LINE_SIZE}
define SYSINFO_CPU_FREQ ${SYSDEP_CPU_FREQ}

ext="(0"
for f in ${SYSDEP_CPU_EXT}
do
  ext="${ext} | $f"
done
ext="${ext})"
define SYSINFO_CPU_EXT "${ext}"

for f in ${SYSDEP_CPU_EXT}
do
  have=`echo "${f}" | sed -e 's/SYSDEP_/SYSDEP_HAVE_/g'`
  define "${have}"
done

cat >> "${fout}" <<EOF

#endif
EOF
